### ISSUE TITLE
Requests sometimes fail

### ISSUE THREAD

**Issue by renatovico** [node-js-libs/node.io#1]
Sometimes in crawler process i catch:

TypeError: Object #<a ClientRequest> has no method 'destroy'
    at /home/ec2-user/.node_libraries/.npm/node.io/0.1.1-15/package/lib/node.io/request.js:102:21

Make simple workaround in this line, adding:

if(request && request.destroy) {
...
}

But I believe that the problem is more severe

**Comment by renatovico** [comment]
An interesting thing:

If I comment is line, I generate one memory leak

**Comment by chriso** [comment]
The API is unclear on how to destroy a request..

For now, I've put in a check for each destroy (in v0.1.1-17). 

I'll put in a better fix once the final 0.3.1 API is out.

-Chris
