### ISSUE TITLE
Scraping example is missing a parenthesis

### ISSUE THREAD

**Issue by gabebw** [node-js-libs/node.io#10]
I'm talking about the node.js Example 1 here: https://github.com/chriso/node.io/wiki/Scraping

Instead of
      } else {
        self.emit(data);
      }
    }

it should be
      } else {
        self.emit(data);
      }
    });

Also, this is less important, but you may want a semicolon after <code>self.exit(err)</code> in the same example.

**Comment by gabebw** [comment]
Er. Turns out I can edit the wiki, so never mind.

**Comment by chriso** [comment]
I was just looking for the missing parentheses and couldn't find it - didn't realise anyone could edit the wiki. Thanks though!
