### ISSUE TITLE
Cookies are automatically added to request of subsequent occurrences of job

### ISSUE THREAD

**Issue by Robdr** [node-js-libs/node.io#100]
It appears that cookies that are received in the first occurrence of a job are automatically attached to requestes of subsequent runs of the same job. Can you create an option to disable this? This creates unwanted behavior for my application.

Thanks!

The following example shows this behavior (use a debugging proxy to see request-headers):

``` javascript
var nodeio = require('node.io');

var rooftrackSearch = {

  input: [1],

    run: function(page_number) {
        var self = this;
        var URL = 'http://www.rooftrack.nl/Rooftrack/layouts/Main.aspx/GetObjectRenderings';
        this.setHeader('Content-Type','application/json; charset=utf-8');
        this.setHeader('Connection','close');
        this.setCookie(); 
        this.post(URL,"{\"pageType\":\"0\",\"pageIndex\":\"0\",\"pageSize\":\"0\"}", function(err, data, headers) {
            this.emit("");
        });
    }
}


nodeio.start(new nodeio.Job({}, rooftrackSearch), {}, function() {
    nodeio.start(new nodeio.Job({}, rooftrackSearch), {}, function() {
        console.log('two requests completed')
    }, false);
}, false);

```

**Comment by chriso** [comment]
Which version are you using? I think this is an issue with the [request](https://github.com/mikeal/request) library having a cookie jar turned on by default. This was turned off in [0.4.9-1](https://github.com/chriso/node.io/commit/adc39f6e6ea2e2f213f45e01105891cd1607e7ac#L1R278).

Cookies should be sent on _nested_ requests but not requests with different elements of input. They should definitely not persist across node.io jobs.

**Comment by Robdr** [comment]
Sorry for the extremely late reply. In 0.4.10 the issue has been solved indeed!
