### ISSUE TITLE
Compiled Coffee Location Pathing Issues

### ISSUE THREAD

**Issue by Akkuma** [node-js-libs/node.io#102]
I've noticed that depending on what directory you call node.io from will result in *_compiled.js being created in the current executing directory. Personally, I think it would be better if node.io chose to compile all scripts in the directory they are actually located in, which would make the behavior very consistent and prevent pathing issues in code. This is a fairly minor issue, but is a bit of a quality of life issue.

**Comment by chriso** [comment]
The temporary file should be deleted on exit but I agree, this could be handled better
