### ISSUE TITLE
Switch to cheerio-soupselect

### ISSUE THREAD

**Issue by Akkuma** [node-js-libs/node.io#103]
Node Soupselect is pretty much dead in the water, over a year of no development and numerous pull requests sitting around, and lags pretty far behind for more advance selectors. It probably would make sense to switch to https://github.com/MatthewMueller/cheerio-soupselect

**Comment by chriso** [comment]
cheerio-soupselect / cheerio are already on the todo list but I'll leave this ticket open until they're in place

**Comment by kopertop** [comment]
This would be great to see cheerio added instead of JSDOM. I've had to switch everything away from getHtml, to just get() and then parse with cheerio myself.
