### ISSUE TITLE
DEBUG: ERR Request failed with (?) Error: Parse Error node.io

### ISSUE THREAD

**Issue by adamramadhan** [node-js-libs/node.io#106]
example scrap site `test.js`

```
var nodeio = require('node.io');
exports.job = new nodeio.Job({
    input: false,
    run: function () {
        var url = "www.test.com/?a=test&b=test&c=hello&date=12-06-2012";
        this.get(url, function(err, data) {
            if (err) {
                this.exit(err);
            } else {
                this.emit(data);
            }
        });
    }
});
```

and run it with

`nodeio test.js` it fails but when i delete the `date=12-06-2012` it somehow work. is there something wrong here?

when i `nodeio --debug` it tells me `?`

`DEBUG: ERR Request failed with (?) Error: Parse Error`

**Comment by chriso** [comment]
Can't seem to reproduce this? It is still an issue?

**Comment by adamramadhan** [comment]
somehow it work. closing for now until i can reproduce this issue.
