### ISSUE TITLE
feature request: switch to jQuery CSS selectors

### ISSUE THREAD

**Issue by ericjang** [node-js-libs/node.io#109]
jQuery offers more powerful CSS selectors. For example, 

$('.somediv').each(function(index,result){
console.log($(this).find(''a'));
});

does not work because:
1) node.io callback function only takes in one argument (result)
2) 'this' points to Node.io Job object instead of the selector element returned.

it should be a simple matter to do $ = require('jquery');

**Comment by chriso** [comment]
You can set the `jsdom` option to true to use jQuery instead of the default node-htmlparser / node-soupselect mashup. Note that this is generally slower because a full DOM instance needs to be spun up on every response.
