### ISSUE TITLE
Error: No elements matching '#resultStats'

### ISSUE THREAD

**Issue by 3even** [node-js-libs/node.io#110]
## When trying to run the keywords.js example I receive the following error:

/usr/local/lib/node_modules/node.io/lib/node.io/dom.js:29
          throw new Error("No elements matching '" + selector + "'");
                ^
Error: No elements matching '#resultStats'
    at [object Object].$ (/usr/local/lib/node_modules/node.io/lib/node.io/dom.js:29:17)
##     at /usr/local/lib/node_modules/node.io/lib/node.io/dom.js:81:33

Node v0.6.15
Node.io v0.4.12

**Comment by xaevir** [comment]
change the selector to this:

var results = $('#subform_ctrl div').last().text.toLowerCase();

**Comment by 3even** [comment]
Danke!
