### ISSUE TITLE
Selector not working as expected.

### ISSUE THREAD

**Issue by LukeChannings** [node-js-libs/node.io#113]
I use $(".someclass > h1") and I get an exception:

/usr/local/lib/node_modules/node.io/lib/node.io/dom.js:29
          throw new Error("No elements matching '" + selector + "'")

however, $(".someclass h1") works without issue, and I can confirm the DOM tree to be:

<div class="someclass">
<h1>Some Text</h1>
</div>

Does the DOM implementation not support the child selector?

**Comment by jonlong** [comment]
Are you using the default selector engine (soupselect)?

If so, I believe it only supports the following:
- type selectors
- class selectors
- id selectors
- attribute selectors
- descendant combinator

[(Reference)](https://github.com/simonw/soupselect)

In your job options, if you make sure to set `jsdom: true` you should be able to use jQuery's selector engine instead.

**Comment by LukeChannings** [comment]
Doesn't appear to be working, here's what I'm using so far: http://pastie.org/4359995, some other questions (this probably isn't the place):
1. when looping over a set of fetched elements, how do you make a deeper selection on each item you're looping through?

For example:

```
$(".some-items").each(function(item) {
    // what I would expect:
    var header = $(item).filter("h1"),
    paragraph = $(item).filter("p")
})
```

I checked the docs but couldn't find anything on that topic.
1. export XML on completed:

I expected to be able to implement the completed method and just do something like:

```
this.write("output.xml", document.toString({/* xmlbuilder options */}))
```

Thank you very much for your help :)

**Comment by jonlong** [comment]
Looks like you might have the `jsdom` option in the wrong spot.  Try putting it in the actual job options, like this:  http://pastie.org/4360028

Also, for your other questions — you're right, someplace like [stackoverflow.com](http://www.stackoverflow.com) is a better fit for this—but I can answer the first.

Basically, if you are using jQuery at this point (which you are if you're enabling jsdom), you would write that `each` method exactly as you would when using jQuery anywhere else.  In your example, you're expecting the element to be returned as a callback value, but that's not how the `each` method works.  Instead, you'd write it like this:

```
$(".some-items").each(function() {
    var header = $(this).find("h1"),
    paragraph = $(this).find("p");
});
```

I replaced your `filter` methods with `find` methods, as they are closer to what you're trying to do syntax-wise here.  If you wanted to use the `filter` method, I think you would have to wrap your selection in a jQuery function like so:

`$("div").filter( $("#unique") )`

Have a look at the jQuery API docs—I've found them to be extremely thorough and helpful: http://api.jquery.com/jQuery.each/

**Comment by chriso** [comment]
@TheFuzzball as Jon said, the default selector engine is node-soupselect. It only supports a subset of the jQuery selectors you might be used to but it's significantly faster and less memory intensive than a full JSDOM instance per scraped page. Enable it with the `jsdom: true` just like Jon showed in the pastie snippet.

As for the jQuery question, I'm not entirely sure. You should be able to find the answer in the jQuery docs or on stackoverflow.com
