### ISSUE TITLE
this.add runs indefinitely unless i'm doing something wrong

### ISSUE THREAD

**Issue by jzevin** [node-js-libs/node.io#124]
I'm trying to dynamically add to the input queue based on args from cli like so:

``` coffeescript
input: [1]
run: (pageNum) ->
    if @options.args[1]
      totalPages = [2..(@options.args[1]/50).ceil()]
      for page in totalPages
        @add page
```

Whatever is added keeps repeating indefinitely.
Am I doing this wrong?

**Comment by erfanimani** [comment]
@phillyDesignr did you manage to fix this?

**Comment by jzevin** [comment]
nope, looks like this repo is no longer being maintained.
