### ISSUE TITLE
Support for multiple output files

### ISSUE THREAD

**Issue by appanp** [node-js-libs/node.io#126]
In some scenarios we require writing to more than one output file, while doing the processing in a job. In this case, we also need to give the file name as handle for indicating where to write.

**Comment by chriso** [comment]
IO requirements that don't fit with the provided convenience methods should be handled using a custom `input()` or `output()` function. Here's an example of multiple output streams.

``` javascript
var file1 = fs.createWriteStream('/path/to/file1')
  , file2 = fs.createWriteStream('/path/to/file2');

var job = new nodeio.Job({
    output: function (rows) {
         file1.write(rows.join('\n'));
         file2.write(rows.join('\n'));
    }
});
```

Have a look at the [wiki](https://github.com/chriso/node.io/wiki/Input---Output) for more information.

**Comment by chriso** [comment]
r nod
