### ISSUE TITLE
Support HTML file in the url for processing static files in file system

### ISSUE THREAD

**Issue by appanp** [node-js-libs/node.io#127]
Currently URL is always assumed to be a network resource. Also, calling parseHtml() directly in the job run() while processing static HTML files recursively in a directory does not seem to work.

**Comment by chriso** [comment]
The URL is passed to the [request](https://github.com/mikeal/request) library which is why `file://` urls might not work.

Can you post a minimal test case with parseHTML failing or at least some example code?

**Comment by zazabe** [comment]
A solution is to setup a local server with NodeJS and provide the content of your local files in the response. I'm doing this for unit tests.

```
var http = require('http');
var fs = require('fs');
var nodeio = require('node.io');

var srv = http.createServer(function (req, res) {
    fs.readFile(__dirname + req.url, { encoding: 'utf8', flag: 'r'}, function(err, data){
        if(err){
            throw err;
        }    
        res.writeHead(200, {'Content-Type': 'text/plain'});
        res.end(data);
    });
});
srv.listen('223344'); 


...
var job = new nodeio.Job({
    input: ['relative/path/to/this/local/file1.html', 'relative/path/to/this/local/file2.html',...],
    run: function(filename){
        this.postHtml('http://localhost:223344/' + filename, function(err, $, data, headers){
            ...
        });     
    }       
});
...
nodeio.start(job, function(){
    srv.close();
});
```

My 2 cents solution ;) 
hope it can help !
