### ISSUE TITLE
mac lion seems that there is something wrong.

### ISSUE THREAD

**Issue by singleseeker** [node-js-libs/node.io#131]
> contextify@0.1.3 install /usr/local/lib/node_modules/node.io/node_modules/jsdom/node_modules/contextify
> node-gyp rebuild

gyp WARN EACCES user "root" does not have permission to access the dev dir "/Users/seeker/.node-gyp/0.8.1"
gyp WARN EACCES attempting to reinstall using temporary dev dir "/usr/local/lib/node_modules/node.io/node_modules/jsdom/node_modules/contextify/.node-gyp"
gyp http GET http://nodejs.org/dist/v0.8.1/node-v0.8.1.tar.gz
gyp http 200 http://nodejs.org/dist/v0.8.1/node-v0.8.1.tar.gz

anyidea?

**Comment by chriso** [comment]
`node-gyp` needs access to the node source and downloads it to `~/.node-gyp/<version>` as necessary.

Try running with `sudo` if you get a permissions error

**Comment by singleseeker** [comment]
> node-gyp rebuild

gyp WARN EACCES user "root" does not have permission to access the dev dir "/Users/seeker/.node-gyp/0.8.1"
gyp WARN EACCES attempting to reinstall using temporary dev dir "/usr/local/lib/node_modules/node.io/node_modules/jsdom/node_modules/contextify/.node-gyp"
gyp http GET http://nodejs.org/dist/v0.8.1/node-v0.8.1.tar.gz
gyp http 200 http://nodejs.org/dist/v0.8.1/node-v0.8.1.tar.gz
  CXX(target) Release/obj.target/contextify/src/contextify.o
  SOLINK_MODULE(target) Release/contextify.node
  SOLINK_MODULE(target) Release/contextify.node: Finished
/usr/local/bin/io -> /usr/local/lib/node_modules/node.io/bin/io
/usr/local/bin/node.io-web -> /usr/local/lib/node_modules/node.io/bin/node.io-web
/usr/local/bin/node.io -> /usr/local/lib/node_modules/node.io/bin/node.io
node.io@0.4.12 /usr/local/lib/node_modules/node.io
├── request@2.9.202
├── coffee-script@1.4.0
├── htmlparser@1.7.6
├── jquery@1.8.2 (navigator@1.0.1, location@0.0.1, xmlhttprequest@1.4.2)
└── jsdom@0.2.19 (cssom@0.2.5, cssstyle@0.2.3, contextify@0.1.3)

i donot konw if this will be work fine.
you know ,i inatall the node.io use "sudo npm install -g node.io",but still comes the permission pb.

**Comment by chriso** [comment]
It looks like the build succeeds so what's the problem?  Try running `node.io -v` to verify.
