### ISSUE TITLE
installation issue on windows 7 x64

### ISSUE THREAD

**Issue by soccer10man** [node-js-libs/node.io#135]
I tried to install node.io by opening the Node.js command window as an administrator but get the following errors. it appears it's complaining about 'python" not install. do i need to install python? Please help.

C:\Users\mike>npm install -g  node.io
npm http GET https://registry.npmjs.org/node.io
npm http 304 https://registry.npmjs.org/node.io
npm http GET https://registry.npmjs.org/htmlparser
npm http GET https://registry.npmjs.org/jquery
npm http GET https://registry.npmjs.org/coffee-script
npm http GET https://registry.npmjs.org/request/2.9.202
npm http GET https://registry.npmjs.org/jsdom
npm http 304 https://registry.npmjs.org/htmlparser
npm http 304 https://registry.npmjs.org/request/2.9.202
npm http 304 https://registry.npmjs.org/coffee-script
npm http 304 https://registry.npmjs.org/jquery
npm http 304 https://registry.npmjs.org/jsdom
npm http GET https://registry.npmjs.org/xmlhttprequest
npm http GET https://registry.npmjs.org/location/0.0.1
npm http GET https://registry.npmjs.org/navigator
npm http GET https://registry.npmjs.org/jsdom
npm http GET https://registry.npmjs.org/contextify
npm http GET https://registry.npmjs.org/nwmatcher
npm http GET https://registry.npmjs.org/cssom
npm http GET https://registry.npmjs.org/cssstyle
npm http GET https://registry.npmjs.org/contextify
npm http 304 https://registry.npmjs.org/xmlhttprequest
npm http 304 https://registry.npmjs.org/navigator
npm http 304 https://registry.npmjs.org/contextify
npm http 304 https://registry.npmjs.org/jsdom
npm http 304 https://registry.npmjs.org/location/0.0.1
npm http 304 https://registry.npmjs.org/nwmatcher
npm WARN package.json nwmatcher@1.3.0 No README.md file found!
npm http 304 https://registry.npmjs.org/cssom
npm http 304 https://registry.npmjs.org/cssstyle
npm http 304 https://registry.npmjs.org/contextify
npm http GET https://registry.npmjs.org/bindings
npm http GET https://registry.npmjs.org/cssom
npm http GET https://registry.npmjs.org/cssstyle
npm http 304 https://registry.npmjs.org/bindings

> contextify@0.1.3 install C:\Users\mike\AppData\Roaming\npm\node_modules\node.i
> o\node_modules\jsdom\node_modules\contextify
> node-gyp rebuild
> 
> contextify@0.1.3 install C:\Users\mike\AppData\Roaming\npm\node_modules\node.i
> o\node_modules\jquery\node_modules\contextify
> node-gyp rebuild

C:\Users\mike\AppData\Roaming\npm\node_modules\node.io\node_modules\jsdom\node_m
odules\contextify>node "C:\Program Files\nodejs\node_modules\npm\bin\node-gyp-bi
n\....\node_modules\node-gyp\bin\node-gyp.js" rebuild

C:\Users\mike\AppData\Roaming\npm\node_modules\node.io\node_modules\jquery\node_
modules\contextify>node "C:\Program Files\nodejs\node_modules\npm\bin\node-gyp-b
in\....\node_modules\node-gyp\bin\node-gyp.js" rebuild
npm http 304 https://registry.npmjs.org/cssstyle
npm http 304 https://registry.npmjs.org/cssom
gyp ERR! gypconfigure error
ERR! configure errorgyp
 ERR! gypstack ERR! Error: Can't find Python executable "python", you can set th
e PYTHON env variable.
 stackgyp  Error: Can't find Python executable "python", you can set the PYTHON
env variable.
ERR! gyp stack     at failNoPython (C:\Program Files\nodejs\node_modules\npm\nod
e_modules\node-gyp\lib\configure.js:113:14)
ERR! gyp stack     at failNoPython (C:\Program Files\nodejs\node_modules\npm\nod
e_modules\node-gyp\lib\configure.js:113:14)
ERR! gypstack      at C:\Program Files\nodejs\node_modules\npm\node_modules\node
-gyp\lib\configure.js:82:11
ERR!gyp  stack     at C:\Program Files\nodejs\node_modules\npm\node_modules\node
-gyp\lib\configure.js:82:11
ERR! gypstack      at Object.oncomplete (fs.js:297:15)
ERR! stack     at Object.oncomplete (fs.js:297:15)
gyp ERR! gypSystem  Windows_NT 6.1.7601
ERR!gyp  System Windows_NT 6.1.7601
ERR! command "node" "C:\Program Files\nodejs\node_modules\npm\node_modules\
\node-gyp\bin\node-gyp.js" "rebuild"
gyp gyp ERR! ERR! commandcwd "node" "C:\Program Files\nodejs\node_modules\np
m\node_modules\node-gyp\bin\node-gyp.js" "rebuild"
 C:\Users\mike\AppData\Roaming\npm\node_modules\node.io\node_modules\jsdom\node_
modules\contextify
gypgyp  ERR!ERR!  node -v v0.8.17
cwdgyp ERR!  C:\Users\mike\AppData\Roaming\npm\node_modules\node.io\node_modules
\jquery\node_modules\contextify
node-gyp -vgyp v0.8.2
 gyp ERR!ERR!  not oknode -v
 v0.8.17
gyp ERR! node-gyp -v v0.8.2
gyp ERR! not ok
npm WARN optional dep failed, continuing contextify@0.1.3
npm ERR! contextify@0.1.3 install: `node-gyp rebuild`
npm ERR! `cmd "/c" "node-gyp rebuild"` failed with 1
npm ERR!
npm ERR! Failed at the contextify@0.1.3 install script.
npm ERR! This is most likely a problem with the contextify package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls contextify
npm ERR! There is likely additional logging output above.

npm ERR! System Windows_NT 6.1.7601
npm ERR! command "C:\Program Files\nodejs\\node.exe" "C:\Program Files\nod
ejs\node_modules\npm\bin\npm-cli.js" "install" "-g" "node.io"
npm ERR! cwd C:\Users\mike
npm ERR! node -v v0.8.17
npm ERR! npm -v 1.2.0
npm ERR! code ELIFECYCLE
npm ERR!
npm ERR! Additional logging details can be found in:
npm ERR!     C:\Users\mike\npm-debug.log
npm ERR! not ok code 0

C:\Users\mike>

**Comment by soccer10man** [comment]
installed python 27.. it passed the python error but still failing to build. maybe, node.io is not supported in windows 7?
anyway, here is the output.

C:\Users\mike>npm install -g node.io
npm http GET https://registry.npmjs.org/node.io
npm http 304 https://registry.npmjs.org/node.io
npm http GET https://registry.npmjs.org/htmlparser
npm http GET https://registry.npmjs.org/jquery
npm http GET https://registry.npmjs.org/coffee-script
npm http GET https://registry.npmjs.org/request/2.9.202
npm http GET https://registry.npmjs.org/jsdom
npm http 304 https://registry.npmjs.org/jquery
npm http 304 https://registry.npmjs.org/coffee-script
npm http 304 https://registry.npmjs.org/jsdom
npm http 304 https://registry.npmjs.org/htmlparser
npm http 304 https://registry.npmjs.org/request/2.9.202
npm http GET https://registry.npmjs.org/location/0.0.1
npm http GET https://registry.npmjs.org/xmlhttprequest
npm http GET https://registry.npmjs.org/navigator
npm http GET https://registry.npmjs.org/jsdom
npm http GET https://registry.npmjs.org/contextify
npm http GET https://registry.npmjs.org/cssom
npm http GET https://registry.npmjs.org/nwmatcher
npm http GET https://registry.npmjs.org/contextify
npm http GET https://registry.npmjs.org/cssstyle
npm http 304 https://registry.npmjs.org/navigator
npm http 304 https://registry.npmjs.org/xmlhttprequest
npm http 304 https://registry.npmjs.org/jsdom
npm http 304 https://registry.npmjs.org/contextify
npm http 304 https://registry.npmjs.org/location/0.0.1
npm http 304 https://registry.npmjs.org/cssom
npm http GET https://registry.npmjs.org/bindings
npm http 304 https://registry.npmjs.org/nwmatcher
npm WARN package.json nwmatcher@1.3.0 No README.md file found!
npm http 304 https://registry.npmjs.org/contextify
npm http 304 https://registry.npmjs.org/cssstyle
npm http GET https://registry.npmjs.org/cssstyle
npm http GET https://registry.npmjs.org/cssom
npm http 304 https://registry.npmjs.org/bindings
npm http 304 https://registry.npmjs.org/cssstyle
npm http 304 https://registry.npmjs.org/cssom

> contextify@0.1.3 install C:\Users\mike\AppData\Roaming\npm\node_modules\node.i
> o\node_modules\jsdom\node_modules\contextify
> node-gyp rebuild
> 
> contextify@0.1.3 install C:\Users\mike\AppData\Roaming\npm\node_modules\node.i
> o\node_modules\jquery\node_modules\contextify
> node-gyp rebuild

C:\Users\mike\AppData\Roaming\npm\node_modules\node.io\node_modules\jsdom\node_m
odules\contextify>node "C:\Program Files\nodejs\node_modules\npm\bin\node-gyp-bi
n\....\node_modules\node-gyp\bin\node-gyp.js" rebuild

C:\Users\mike\AppData\Roaming\npm\node_modules\node.io\node_modules\jquery\node_
modules\contextify>node "C:\Program Files\nodejs\node_modules\npm\bin\node-gyp-b
in\....\node_modules\node-gyp\bin\node-gyp.js" rebuild
Building the projects in this solution one at a time. To enable parallel build,
please add the "/m" switch.
Building the projects in this solution one at a time. To enable parallel build,
please add the "/m" switch.
C:\Users\mike\AppData\Roaming\npm\node_modules\node.io\node_modules\jquery\node
_modules\contextify\build\contextify.vcxproj(18,3): error MSB4019: The imported
 project "C:\Microsoft.Cpp.Default.props" was not found. Confirm that the path
in the <Import> declaration is correct, and that the file exists on disk.
gyp ERR! build error
gyp ERR! stack Error: `C:\Windows\Microsoft.NET\Framework64\v4.0.30319\msbuild.e
xe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Program Files\nodejs\node_modules\
npm\node_modules\node-gyp\lib\build.js:255:23)
gyp ERR! stack     at ChildProcess.EventEmitter.emit (events.js:99:17)
gyp ERR! stack     at Process._handle.onexit (child_process.js:678:10)
gyp ERR! System Windows_NT 6.1.7601
gyp ERR! command "node" "C:\Program Files\nodejs\node_modules\npm\node_modu
les\node-gyp\bin\node-gyp.js" "rebuild"
gyp ERR! cwd C:\Users\mike\AppData\Roaming\npm\node_modules\node.io\node_modules
\jquery\node_modules\contextify
gyp ERR! node -v v0.8.17
gyp ERR! node-gyp -v v0.8.2
gyp ERR! not ok
C:\Users\mike\AppData\Roaming\npm\node_modules\node.io\node_modules\jsdom\node_
modules\contextify\build\contextify.vcxproj(18,3): error MSB4019: The imported
project "C:\Microsoft.Cpp.Default.props" was not found. Confirm that the path i
n the <Import> declaration is correct, and that the file exists on disk.
gyp ERR! build error
gyp ERR! stack Error: `C:\Windows\Microsoft.NET\Framework64\v4.0.30319\msbuild.e
xe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Program Files\nodejs\node_modules\
npm\node_modules\node-gyp\lib\build.js:255:23)
gyp ERR! stack     at ChildProcess.EventEmitter.emit (events.js:99:17)
gyp ERR! stack     at Process._handle.onexit (child_process.js:678:10)
gyp ERR! System Windows_NT 6.1.7601
gyp ERR! command "node" "C:\Program Files\nodejs\node_modules\npm\node_modu
les\node-gyp\bin\node-gyp.js" "rebuild"
gyp ERR! cwd C:\Users\mike\AppData\Roaming\npm\node_modules\node.io\node_modules
\jsdom\node_modules\contextify
gyp ERR! node -v v0.8.17
gyp ERR! node-gyp -v v0.8.2
gyp ERR! not ok
npm WARN optional dep failed, continuing contextify@0.1.3
npm ERR! contextify@0.1.3 install: `node-gyp rebuild`
npm ERR! `cmd "/c" "node-gyp rebuild"` failed with 1
npm ERR!
npm ERR! Failed at the contextify@0.1.3 install script.
npm ERR! This is most likely a problem with the contextify package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls contextify
npm ERR! There is likely additional logging output above.

npm ERR! System Windows_NT 6.1.7601
npm ERR! command "C:\Program Files\nodejs\\node.exe" "C:\Program Files\nod
ejs\node_modules\npm\bin\npm-cli.js" "install" "-g" "node.io"
npm ERR! cwd C:\Users\mike
npm ERR! node -v v0.8.17
npm ERR! npm -v 1.2.0
npm ERR! code ELIFECYCLE
npm ERR!
npm ERR! Additional logging details can be found in:
npm ERR!     C:\Users\mike\npm-debug.log
npm ERR! not ok code 0

C:\Users\mike>

**Comment by chriso** [comment]
It looks like `node-gyp` (a required part of the node platform) is failing to build the `contextify` extension which is used by one of the `node.io` deps.

```
contextify@0.1.3 install C:\Users\mike\AppData\Roaming\npm\node_modules\node.io\node_modules\jquery\node_modules\contextify
node-gyp rebuild
C:\Users\mike\AppData\Roaming\npm\node_modules\node.io\node_modules\jquery\node
modules\contextify\build\contextify.vcxproj(18,3): error MSB4019: The imported
project "C:\Microsoft.Cpp.Default.props" was not found. Confirm that the path
in the declaration is correct, and that the file exists on disk.
gyp ERR! build error
gyp ERR! stack Error: C:\Windows\Microsoft.NET\Framework64\v4.0.30319\msbuild.exe failed with exit code: 1
```

You'll have to create an issue at either the [node-gyp](https://github.com/TooTallNate/node-gyp/issues) or [npm](https://github.com/isaacs/npm/issues) for more help.

**Comment by xverges** [comment]
I was having the same issue doing "npm install contextify": it was caused by my environment.

To have node-gyp working on Windows7 64 you have to install, in the following order (as specified by the last item in the list)
1. Visual Studio 2010
2. Windows SDK 7.1
3. Visual Studio 2010 SP1
4. Visual C++ 2010 SP1 Compiler Update for the Windows SDK 7.1 

You can get the links from the readme in https://github.com/TooTallNate/node-gyp
