### ISSUE TITLE
any way to loop through parent elements and get their children data?

### ISSUE THREAD

**Issue by ttback** [node-js-libs/node.io#138]
I am trying to use node.io to do something like $(''entry title).each(title){ this.emit(title.text);}
but instead of doing multiple .each() calls to build the record for each entry,
i am trying to make it work like
$('entry').each(entry){
 $('title', entry)
}

But it isn't working for me right now. When I try to change  $('title', entry) to  $('title', entry.rawtext), I just get an array of all the tags [{raw: ....}, {raw:....}]. I can pull it off with some belt library such as valentine or underscore to process the collection, but that feels way over board. 

Could you offer some other ideas?

**Comment by chriso** [comment]
Note that you can't call `emit()` more than once.

Why won't the following work?

``` javascript
var titles = [];
$('entry title').each(title) {
    titles.push(title.text);
});
this.emit(titles);
```

**Comment by ttback** [comment]
didn't know about no emit() more than once. Would love to learn more.

Your code worked for me, but I wanted to improve it to be var entries=[]
instead of end up with arrays of attributes of entries. After playing with it for a hour, I kinda figured it out myself now, by using the $('title', context) seems to work fine. Thanks for responding. :)

**Comment by chriso** [comment]
No problem. There's a lot of info available in the [wiki](https://github.com/chriso/node.io/wiki)

**Comment by ttback** [comment]
yea, there's a lot to learn, just want to get these basics working first for a quick demo. :)
This is by far the shortest amount of time required for me to make a scrapper work beside doing it through command line. Keep up the good work!
