### ISSUE TITLE
Trouble replacing <br />

### ISSUE THREAD

**Issue by ttback** [node-js-libs/node.io#139]
When I output result.fulltext, I have following in console.
<br />Where: Blah blah blah
<br />Event: Blah blah blah

But when i try to use str.replace('<br />', ""), nothing happens...I am a little confused, do you have experience with errors like this?

**Comment by chriso** [comment]
I can't help you without some sort of context here. `result.fulltext` returns a string, so replace should works as expected. Note that `replace('<br />', '')` will only replace the first occurrence. To replace _all_ occurrences use `replace(/<br \/>/g, '')`

**Comment by ttback** [comment]
Exactly where I messed up, I forgot that in js, str.replace() is different from java, thank you!
