### ISSUE TITLE
ERROR: path.exists is now called `fs.exists`.

### ISSUE THREAD

**Issue by vjpr** [node-js-libs/node.io#145]
After installing node.io I get this message when running the Hello World job from the Getting Started guide. I am running node version 0.8.12.

**Comment by chriso** [comment]
There's no `path.exists` or `fs.exists` calls in the library but there might be a few in older dependencies.

```
/tmp/node.io (air) $ grep -r 'path\.exists' **/*.js
node_modules/coffee-script/lib/coffee-script/cake.js:  existsSync = fs.existsSync || path.existsSync;
node_modules/coffee-script/lib/coffee-script/command.js:  exists = fs.exists || path.exists;
node_modules/jquery/node_modules/contextify/node_modules/bindings/bindings.js:  , exists = fs.existsSync || path.existsSync
node_modules/jsdom/node_modules/contextify/node_modules/bindings/bindings.js:  , exists = fs.existsSync || path.existsSync
```

Try removing `node_modules` and reinstalling with `npm install`

**Comment by vjpr** [comment]
I am installing globally.

I tried `npm install -g --force node.io` but it did not fix it.

I get the same message in other projects but it does not error, its just a
warning. Anything that could be causing it to error instead of warning? The
only difference I can see is that its globally installed.

**Comment by chriso** [comment]
You'll need to update both the global node.io copy (for the cli tool), and the copy in your local node_modules directory (for when you `require('node.io')`).

``` bash
$ npm uninstall -g node.io && npm uninstall node.io
$ npm install -g node.io && npm install node.io
```

Again, there's no `path.exists` calls anywhere in the library, and when I do a fresh install there's no calls in any of the dependencies either.

**Comment by vjpr** [comment]
Okay. Must be a problem on my end then. Especially since I'm getting these messages in other modules.
