### ISSUE TITLE
Support Request:  Getting text or media from link

### ISSUE THREAD

**Issue by nikhildaga** [node-js-libs/node.io#147]
In facebook or twitter or google+ : whenever a user posts a link, it shows summary if the link is an article, an image if its image link and video if its youtube url, etc.

Can node.io be useful in implementing this functionality?

Thanks.

**Comment by chriso** [comment]
Yes, node.io can be used to implement this sort of summary. Node.io only provides the framework for scraping and parsing HTML; you'll need to write the higher-level parsing logic yourself.
