### ISSUE TITLE
Save example in page 'Scraping' doesn't work

### ISSUE THREAD

**Issue by wildeyes** [node-js-libs/node.io#155]
% node.io -s save "http://www.google.com/" > google.html 
ERROR: The job could not be found.

Any idea why? Installed Node.io using npm locally and globally.

**Comment by chriso** [comment]
You probably forgot to create the file `save.js` like it says to on the wiki [page](https://github.com/chriso/node.io/wiki/Scraping).

When calling `node.io foo` the process will first look for a file called `foo.js` in the current working directory.

**Comment by wildeyes** [comment]
Oh. Because of the way the command is presented, I thought it was a built-in one, Thanks!
