### ISSUE TITLE
Object #<Object> has no method split()

### ISSUE THREAD

**Issue by ryanwinchester** [node-js-libs/node.io#156]
Trying to scrape a webpage I have for example:

var items = [];

$('a.tooltip').each(function() {
                var item = $(this).attr('rel');
                items.push( item );
            });

this.emit(items);

gives me an error about Object #<Object> has no method split()

**Comment by wildeyes** [comment]
Please try to post an http://sscce.org/.
If I could reproduce your problem, I could help you fix it.

**Comment by chriso** [comment]
I need more information than what you've provided.
- What url were you trying to scrape?
- What's the stack trace?
- Can you post your entire script?

**Comment by ryanwinchester** [comment]
I gave up on this one for a while. If I go back to it I will get all the info requested.
