### ISSUE TITLE
Distributed Scraping with Node.io - still on roadmap?

### ISSUE THREAD

**Issue by victorhooi** [node-js-libs/node.io#158]
Hi,

I was wondering about Distributed Scraping and Node.IO.

The wiki mentioned it's "Coming soon", and there's also this issue (https://github.com/chriso/node.io/issues/24) from a year ago which mentions it (although I wasn't able to find the node.io-v2 repo mentioned).

Is this still in the pipeline?

Is Node.IO still active? Is there a roadmap or a todo somewhere?

Cheers,
Victor

**Comment by chriso** [comment]
The development of features has always been based on my own needs. I haven't got time to add any extra features at this stage, especially not one as big as the distributed scraping, unless someone can sponsor the development.
