### ISSUE TITLE
Does node.io honor robots.txt

### ISSUE THREAD

**Issue by vumaasha** [node-js-libs/node.io#159]
Hi,
Does node.io obey the robots.txt exclusion standard, described at http://www.robotstxt.org/wc/exclusion.html#robotstxt and
 robots META tag, as described at http://www.robotstxt.org/wc/meta-user.html? If not how to achieve this with node.io?

**Comment by chriso** [comment]
The library provides the lower-level functionality required to make requests, parse HTML, handle qeueing, concurrency etc. The user is largely responsible for building scraping infrastructure on top of these lower-level constructs. Parsing and respecting robots.txt is one of those things that the user must account for.
