### ISSUE TITLE
Jobs might not always complete when job.options.max > 1

### ISSUE THREAD

**Issue by psmithuk** [node-js-libs/node.io#16]
Hi Chris,

I think the Timer reset code in `pullInput` might sometimes prevent the `complete` event from being emitted. The reliability seems to be related to the size of the input, the max threads and the response speed for the last few requests.

My limited async debugging skills mean I've filled my local version of node.io with `status('blah','debug')` calls to what's happening. It seems that when there's no more input data left to pull there could be requests still running, and if they don't complete within the 300ms before the next check in `handle_input()` then it's possible that the crucial final check is never made. 

By changing line 129 in `process_master.js` from:

```
if (completeCheckInterval) {
    clearInterval(completeCheckInterval);
}
```

to something like:

```
if (completeCheckInterval && job.input.length > pull) {
    clearInterval(completeCheckInterval);
}
```

...it works each time, regardless of `job.options.max` or network conditions. In fact, removing that block is also fine as it only normally takes a few seconds for the last few threads to finish.

I'm using node.io within other node scripts. I run my jobs using `nodeio.start(job, options, callback, true)` and I'm providing a `job.input()` to load data from a filename passed in `options.args`. Not sure whether that would make a difference to either a) the way the input data is collected; or b) the behaviour of `complete`.

I can try and write some test scripts to recreate the problem I'm having if you think the issue is elsewhere?

I've found node.io to be really useful, thanks for sharing it. Let me know if you need a hand with any documentation, examples etc. I would love to contribute if I can.

Many thanks
Paul

**Comment by chriso** [comment]
Hi Paul, thanks for the feedback. I'm quite busy at the moment but will try and look into the problem ASAP. If the addition of `&& job.input.length > pull` seems to help then keep using it - I'll investigate when I can. I've recently been contracted by a company to build a commercial scraping solution using node.io (and continue development of the framework) so expect some updates soon!

**Comment by chriso** [comment]
Try the latest version and see if it fixes it

**Comment by psmithuk** [comment]
Hi Chris, all looks good so far. I've run about a dozen or so tests of varying sizes and all have completed as hoped. Many thanks for looking at this, I'll let you know if I see any more issues with my testing.
