### ISSUE TITLE
file descriptors do not close using write method 

### ISSUE THREAD

**Issue by aarsakian** [node-js-libs/node.io#160]
I was running out of available file descriptors while parsing and saving massively to files.
This behavior was gone after I closed the WriteStream(), Specifically I added at line 411 of lib/node.io/io.js  the following:
self.output_streams[file].end()

I do not know if this is error or bad usage of apis since I am new to node.js ecosystem.

**Comment by chriso** [comment]
This is likely a bug. The stream API has changed significantly since I wrote the library (which was somewhere around node v0.4)
