### ISSUE TITLE
$("html")

### ISSUE THREAD

**Issue by edasque** [node-js-libs/node.io#18]
Just a quick question. I am trying to get $("html") and while $("body") or $("head") seem to work, $("html") doesn't. Any idea?

```
    throw new Error("No elements matching '" + selector + "'");
          ^
```

Error: No elements matching 'html'
    at [object Object].$ (/usr/local/lib/node/.npm/node.io/0.2.2-5/package/lib/node.io/dom.js:22:15)...

**Comment by chriso** [comment]
This is a problem with [node-soupselect](https://github.com/harryf/node-soupselect) - I'll file a report with the creator, Harry. In the mean time, set the `jsdom` option to true as per [here](https://github.com/chriso/node.io/wiki/API---Job-Options). This will use the alternative parser (JSDOM) and set jQuery as the selector engine. Let me know if you have any more trouble.

**Comment by edasque** [comment]
Have you been able to fill in the bug with soupselect?

**Comment by chriso** [comment]
I've tested soupselect with $('html') and it works as expected:

```
var data = '<html><head></head><body></body></html>';
job.parseHtml(data, function(err, $, data) {
    if (err) throw err;
    console.log($('html'));
});
```

Which outputs:

```
{ raw: 'html',
  data: 'html',
  type: 'tag',
  name: 'html',
  children: 
   [ { raw: 'head', data: 'head', type: 'tag', name: 'head' },
     { raw: 'body', data: 'body', type: 'tag', name: 'body' },
     each: [Function],
     odd: [Function],
     even: [Function],
     first: [Function],
     last: [Function],
     filter: [Function],
     has: [Function] ],
  rawtext: [Getter],
  text: [Getter],
  striptags: [Getter],
  fulltext: [Getter],
  innerHTML: [Getter] }
```

Can you obtain the actual HTML and send me a copy so I can test it? Instead of running `this.getHtml(url, callback)` just run `this.get(url,function(err,data){console.log(data);});` and check that the `<html>` tag looks ok

**Comment by edasque** [comment]
so I tried:

var url = 'http://www.google.com/search?q=node.io';

```
this.getHtml(url,
function(err, $) {

    console.log($('html'));


}); 
```

Which failed because... that page doesn't have a <html> tag for some reason...

**Comment by chriso** [comment]
I believe it's something that google has implemented lately to reduce bandwidth. If the html5 doctype is there (`<!doctype html>`) then the actual html tag (among others) isn't required. Read [this](http://www.w3schools.com/html5/tag_doctype.asp) and [this](http://news.ycombinator.com/item?id=2047065) for more info
