### ISSUE TITLE
Problem with request.js

### ISSUE THREAD

**Issue by phpnode** [node-js-libs/node.io#19]
There seems to be a problem with request.js, handling certain URLs, e.g. 
http://investing.businessweek.com/research/stocks/snapshot/snapshot.asp?capId=101648

I'm trying to scrape a list of URLs, but this URL consistently fails with an error 'EBADNAME, Misformatted domain name'

My code is here, (it's forcing this URL so you don't need to supply any input to see the issue)
https://gist.github.com/833888

ncb000gt kindly supplied a dump of the output of urlparse, which seems to get called twice, the second time it runs the URL gets corrupted:
https://gist.github.com/833921

**Comment by chriso** [comment]
Running with the `--debug` switch shows the problem:

```
~/Documents$ node.io --debug businessweek
DEBUG: Running job "businessweek"
DEBUG: Running 1 worker..
DEBUG: GET http://investing.businessweek.com/research/stocks/snapshot/snapshot.asp?capId=101648 (request 5109)
DEBUG:   | GET /research/stocks/snapshot/snapshot.asp?capId=101648 HTTP/1.1
DEBUG:   | Accept: */*
DEBUG:   | Accept-charset: ISO-8859-1,utf-8;q=0.7,*;q=0.3
DEBUG:   | User-agent: node.io
DEBUG:   | Host: investing.businessweek.com
DEBUG: 302 http://investing.businessweek.com/research/stocks/snapshot/snapshot.asp?capId=101648 (response 5109)
DEBUG:   | Cache-control: private
DEBUG:   | Connection: close
DEBUG:   | Date: Fri, 18 Feb 2011 23:21:43 GMT
DEBUG:   | Content-length: 171
DEBUG:   | Content-type: text/html
DEBUG:   | Expires: Fri, 18 Feb 2011 23:20:43 GMT
DEBUG:   | Location: ../../stocks/private/snapshot.asp?privcapId=101648
DEBUG:   | Server: Microsoft-IIS/6.0
DEBUG:   | X-powered-by: ASP.NET
DEBUG:   | P3p: CP="PHY ONL UNI PUR FIN COM NAV INT DEM STA HEA CUR ADM DEV OUR IND"
DEBUG:   | Set-cookie: 1663%5F0=C6B9BD543F8A83D13DCE7DE855B4F1B6; path=/
```

The request returns a 302 redirect to `../../stocks/private/snapshot.asp?privcapId=101648` and I haven't geared node.io to handle relative redirects. I'll post a fix soon thanks!

**Comment by chriso** [comment]
This is fixed in [this commit](https://github.com/chriso/node.io/commit/db7994b749b43aef3101d27a6d1ae5daa3f64f54) and `v0.2.2-6`
