### ISSUE TITLE
Distributing work

### ISSUE THREAD

**Issue by samdelagarza** [node-js-libs/node.io#21]
My whole problem with screen scraping is that my ip eventually gets blocked. It would be great to be able to create a list of urls to push work out to ( as slaves) or to publish a URL for clients (browsers) to pull work from a queue. 

So in practice I could create an account on no.de which runs my server, tell it which slaves are available (ip or urls) and have it publish a URL for client side workers. This would certainly help me work around ip blocking. 

Have you seen map-crowd-reduce (node.js project)?

**Comment by chriso** [comment]
Hi Sam,

If your IP is getting blocked, distributing work across a few IPs will likely lead to the same result. I suggest looking at proxying your requests or using something like Amazon's elastic IP's with their EC2 service for changing your IP when it gets blocked.

As for distributing work, it's something I plan on implementing when I have some free time - that said, it may take a lot of work and I don't have a great deal of free time so there's no ETA. In the mean time I'd suggest using something like Redis or an RDBMS and instruct each slave to pull input from a common store/table. 

I have seen map-crowd-reduce - it's a cool project but I'm sure that distributing node.io work to the browser would raise some legal issues ;)

-Chris
