### ISSUE TITLE
Distributed processing / scraping

### ISSUE THREAD

**Issue by chriso** [node-js-libs/node.io#24]

**Comment by ghost** [comment]
Hi, mind sharing some thoughts about how you plan to implement!? Thanks in advance.

**Comment by chriso** [comment]
Not entirely sure as of yet. I've got a few ideas and have had some advice re using external libs like ZeroMQ, RabbitMQ. Development of node.io has always been based on my own needs - I haven't (as of yet) required any more performance than I squeeze out of a single box / node.io instance, so no plans on implementing this in the short term.

**Comment by chriso** [comment]
This will come in node.io-v2 sometime soon (separate repo)
