### ISSUE TITLE
Module does not contain job

### ISSUE THREAD

**Issue by mationai** [node-js-libs/node.io#26]
I'm testing out the save google.html example and it's giving me the following error:

ERROR: Module does not contain job "http://www.google.com/"

Tried both js & coffee versions and ran:  node.io -s save "http://www.google.com/" > google.html

node.io: 0.2.9-2
node.js: 0.5.0-pre

**Comment by mationai** [comment]
Correction, js version did work, just coffee didn't work.

coffeescript: 1.1.1

**Comment by mationai** [comment]
Got it, example missing:

@class = SavePage
@job = new SavePage()

Leaving issue open so you update doc.  Also while you're at it, the -g option to install didn't work me..

**Comment by ttilley** [comment]
random and mostly unrelated aside: npm has a package.json attribute that states something should be installed globally unless told otherwise (as far as I understand it), and display a warning when installed locally. {"preferGlobal":true}

https://github.com/isaacs/npm/blob/master/doc/json.md

**Comment by chriso** [comment]
Thanks, fixed.

@ttilley - I updated `package.json` 2 weeks ago in [this commit](https://github.com/chriso/node.io/commit/619ea733feb0e7b68940326d9ce51be8d30e6233) to use the new `preferGlobal` op
