### ISSUE TITLE
Failed to load job "hello"

### ISSUE THREAD

**Issue by tomhaymore** [node-js-libs/node.io#28]
I'm trying to run the intro job hello.js but when I run this command:

```
node.io hello
```

I get this output:

```
 ERROR: Failed to load job "hello". Please check that the job exists and compiles correctly.
```

When I debug:

```
DEBUG: {"stack":"Error: Cannot find module 'node.io'\n    at Function._resolveFilename (module.js:322:11)\n    at Function._load (module.js:267:25)\n    at require (module.js:351:19)\n    at Object.<anonymous> (/Users/username/Documents/Nodejs/hello.js:1:75)\n    at Module._compile (module.js:407:26)\n    at Object..js (module.js:413:10)\n    at Module.load (module.js:339:31)\n    at Function._load (module.js:298:12)\n    at require (module.js:351:19)\n    at [object Object].loadJob (/opt/local/lib/node_modules/node.io/lib/node.io/processor.js:294:37)","message":"Cannot find module 'node.io'"}
```

However, `echo "mastercard.com" | node.io -s pagerank` works just fine just as `node.io query "http://www.reddit.com/" a.title` does.

**Comment by chriso** [comment]
Strange. What version of NPM, Node.JS and node.io are you using?

Have you tried reinstalling node.io?

npm < 1.0.0:

```
sudo npm install node.io
```

npm >= 1.0.0

```
sudo npm install -g node.io
```

**Comment by tomhaymore** [comment]
Thanks!  I reinstalled and then had to rearrange my folders a bit but now it's working.

**Comment by rvavruch** [comment]
Hi tchaymore, I'm having the same problem. Can you specify exactly what you did to fix this?

**Comment by tomhaymore** [comment]
Now I'm not sure I remember.  I think I uninstalled everything (including
NPM) and then made sure that I was installing everything in the same folder
and it worked.  I think.

On Tue, Aug 23, 2011 at 5:01 AM, rvavruch <
reply@reply.github.com>wrote:

> Hi tchaymore, I'm having the same problem. Can you specify exactly what you
> did to fix this?
> 
> ## 
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/chriso/node.io/issues/28#issuecomment-1879122

## 

Thomas Haymore
Stanford Law School
Stanford University, Management Science & Engineering
Twitter: @tchaymore

**Comment by chriso** [comment]
Try running `npm install node.io` in the same directory as the job you're trying to run
