### ISSUE TITLE
use jquery for object $

### ISSUE THREAD

**Issue by madhums** [node-js-libs/node.io#30]
Is it possible to  use jQuery in the place of $ object? OR is there any way I can create a jQuery window object with the help of $ object?

<pre>
var nodeio = require('node.io'), options = {timeout: 10},
    jQuery = require('jquery');

exports.job = new nodeio.Job(options, {
    input: ['hello', 'foobar', 'weather'],
    run: function (keyword) {
        this.getHtml('http://www.google.com/search?q=' + encodeURIComponent(keyword), function (err, $) {

            // SOMEHOW CREATE THE JQUERY OBJECT USING $

            var results = $('#resultStats').text.toLowerCase();
            this.emit(keyword + ' has ' + results);
        });
    }
});
</pre>

**Comment by chriso** [comment]
Use the `jsdom` option to enable jsdom/jquery. jQuery is accessible through `$`

**Comment by madhums** [comment]
when I use jsdon : true option, I get $ is undefined. node.io version is 0.3.0, jquery version is 1.5.1 and jsdom version is 0.2.0. Do you have any idea why I am getting this error?
