### ISSUE TITLE
jquery not working with jsdom true

### ISSUE THREAD

**Issue by madhums** [node-js-libs/node.io#31]
As you suggested earlier, I tried using <code>jsdom: true</code> option, but nothing happens. It all works fine when I use <code>jsdom:false</code>. When I use it with jsdom: true, I always get a timeout error.

<pre>
var nodeio = require('node.io');
var options = {
      max: 20,
      timeout: 20, 
      jsdom: true
    };

exports.job = new nodeio.Job(options, {
    input: false,
    run: function () {
        this.getHtml('http://node.io/', function (err, $, data) {
          if(err) this.exit(err);
          this.emit("jquery object:"+ $);
        });
    }
});
</pre>

I am using 

<pre>
node.io -v 0.3.0
jquery -v 1.5.1
jsdom -v 0.2.0
</pre> 

I din't have the permission to reopen the previous issue so creating a new one...

**Comment by madhums** [comment]
ok, i figured the problem.  After commenting out the below lines in <code>lib/node.io/dom.js</code> the timeout error stopped!

<pre>
    //window.onload = function() {
        callback.apply(self, [null, $, data, headers, response]);
    //}
</pre>


can anyone throw some light?

**Comment by chriso** [comment]
It seems that [this pull request](https://github.com/chriso/node.io/commit/df3c907e4ceb2d0f5b4a788ea8cf42e3dcbc614f) broke JSDOM integration.

[This commit](https://github.com/chriso/node.io/commit/d9059a8ef1c71ab7f83dcfedd2521cd907eafea8) reverts the change. `npm install -g node.io` to install the latest version (0.3.1).
