### ISSUE TITLE
Working with proxies

### ISSUE THREAD

**Issue by rvanrooy** [node-js-libs/node.io#32]
Hi, Can you provide some code that shows how one would use a proxy? I realize that the code is not tested, but I'm not even sure how to include it in the ob options.

I'm assuming something like  

new nodeio.HttpProxy("http://proxy:port")

is how it's meant to function?

Thanks for this excellent library. If I could get it to work through the proxy, it would be excellent.

**Comment by chriso** [comment]
Hey, sorry for the delay in getting back to you. HTTP proxy support is 100% untested but I've made a few changes in `0.3.3`. Try this:

_test.js_

``` javascript
var nodeio = require('node.io');

var options = {
    proxy: 'http://127.0.0.1:8080' //Your proxy host
}

exports.job = new nodeio.Job(options, {
    input: false,
    run: function () {
        this.get('http://www.google.com/', function (err, data) {
            this.emit(data);
        });
    }
});
```

``` bash
io --debug test.js
```

**Comment by rvanrooy** [comment]
Hi Chris. Thank you so much for getting back to me. Unfortunately,
this didn't work for me.

Thanks for replying.

On Wed, Jun 22, 2011 at 12:52 PM, chriso
reply@reply.github.com
wrote:

**Comment by blup** [comment]
I tested it yesterday with a public proxy and it seemed to work fine.

**Comment by rvanrooy** [comment]
This is the output from the code that chriso provided.

DEBUG: Running 1 worker..
DEBUG: GET http://localhost:3128/ (request 83632)
DEBUG:   | GET / HTTP/1.1
DEBUG:   | Accept: _/_
DEBUG:   | Accept-charset: ISO-8859-1,utf-8;q=0.7,*;q=0.3
DEBUG:   | User-agent: node.io
DEBUG:   | Host: www.google.com
DEBUG: ERR Request 83632 timed out (http://localhost:3128/)
DEBUG: ERR Request 83632 failed with (undefined) Error: socket hang up
(http://localhost:3128/)
OK: Job complete

I can curl through the proxy, and npm works through the proxy. When
connecting from home server (no proxy) it works fine. If you have any
thoughts, would like to hear them.

Thanks,

On 14 July 2011 15:22, blup
reply@reply.github.com
wrote:

**Comment by chriso** [comment]
Hey sorry this has been dragging along, I don't have a great deal of time to test it. I tested a request through a proxy after [this commit](https://github.com/chriso/node.io/commit/60147773e8f48465f8f0d77df2150f206bf3f6c3) and it seemed to work correctly. Could you test it again and let me know how you go?

**Comment by rvanrooy** [comment]
After this change, it works beautifully.

Thanks!

On 19 July 2011 13:45, chriso
reply@reply.github.com
wrote:

**Comment by rvanrooy** [comment]
Hi Chriso.  I realize you don't have too much time, but just thought I'd raise an issue with the current implementation. It seems that only the first input value goes through the proxy, but subsequent inputs in the same job have the host rewritten so it tries to actually get the data from the proxy and not through the proxy. If I can figure out how to build node.io, I'll try have a look and see if I can figure it out myself.

Thanks

-edit I mistakenly sent this from another account.

**Comment by pbowyer** [comment]
I can confirm that the first request goes through the proxy, but following ones don't. Haven't spotted what the issue is in the source though!

**Comment by blup** [comment]
pbowyer, do you mind if i ask you you found this? thanks.

**Comment by pbowyer** [comment]
blup: multiple tests with a local version of SQUID and also with Charles Proxy, monitoring where they go... but mostly because follow-up requests fail since they are querying the wrong URL. Debug mode shows the error, the proxies merely provide a view of what's happening.

**Comment by blup** [comment]
i can confirm what pbowyer said. i thought the proxy was working (blindly), but i just tested against a server of mine and with netstat i get my home IP, not the proxy i set up.

**Comment by rvanrooy** [comment]
Just want to note that while v0.3.5 and v0.3.6 got the first request in the job through the proxy, but not subsequent ones, v0.3.7 does not allow any requests to get through correctly.

I've tracked it to commit 7b602dfa5cd3b719e1600a6953cb842f7f8849c5, specifically line 290 in lib/node.io/request.js.
commenting it out once again allows the first request through the proxy. It still doesn't give me insight into what changes between the first request and the rest, but I'm still trying to figure that out.

Update:
after doing some logging, It seems like there is a recursion or loop issue at play. I put a console.log on line 598 in request.js to output the value of urlhost in the function HttpProxy.

If I have 3 requests to google.com,

The first one (which works) outputs,
Host: google.com

The second one:
Host: google.com
Host: localhost:3128

The third one:
Host: google.com
Host: localhost:3128
Host: localhost:3128

It seems that for input n, the HttpProxy function is called n times.

Does anyone know where the looping comes from?

Thanks,

**Comment by phillro** [comment]
I believe I am experiencing this problem, but with on the first request as well as all subsequent ones:

io --debug jobs/proxyTest2.js http://google.com/news
DEBUG: Running 1 worker..
DEBUG: GET http://192.168.2.1:8123/news (request 33381)
DEBUG:   | GET /news HTTP/1.1
DEBUG:   | Accept: _/_
DEBUG:   | Accept-charset: ISO-8859-1,utf-8;q=0.7,*;q=0.3
DEBUG:   | User-agent: node.io
DEBUG:   | Host: google.com:8123
DEBUG: 404 http://192.168.2.1:8123/news (response 33381)
DEBUG:   | Connection: close
DEBUG:   | Date: Fri, 07 Oct 2011 20:25:42 GMT
DEBUG:   | Content-type: text/html
DEBUG:   | Content-length: 435
DEBUG:   | Expires: 0
DEBUG:   | Cache-control: no-cache
DEBUG:   | Pragma: no-cache
DEBUG: ERR Request 33381 failed with code 404 (http://192.168.2.1:8123/news)
ERROR: 404

**Comment by chriso** [comment]
I've ported the entire request process to use [mikeal/request](https://github.com/mikeal/request) as of `v0.4.0`. HTTP proxies are now 100% supported using the `proxy` option. Let me know if you have any issues.

**Comment by rvanrooy** [comment]
Seems to have fixed the issue. Thanks!
