### ISSUE TITLE
Unable to add extra methods

### ISSUE THREAD

**Issue by kclay** [node-js-libs/node.io#33]
I i'm having a real problem trying to add extra methods to a job. Currently i'm using nodeio.JobProto.prototype to add my methods for my base class , but the problem comes when i try to access said function in the 'run' method stating that the method cannot be found.

nodeio.JobProto.prototype.test=function(){
this.debug("hello world");
}
new nodeio.Job({
   run:function(){
     this.test();
})

I got around this my mixin my methods in the first run call but this isnt the best way since the methods are referencing the same function in all job instances

**Comment by chriso** [comment]
Hey can you try this now?

_test.js_

``` javascript
var nodeio = require('node.io');

nodeio.JobProto.prototype.customfunc = function () {
    console.log('in customfunc()');
}

exports.job = new nodeio.Job({
    input: false,
    run: function () {
        this.customfunc();
        this.emit();
    }
});
```

``` bash
$ node.io test.js
```

It should output: _in customfunc()_

If you're looking to share methods between jobs, you might want to define a base job and then use `job.extend(options, methods)` rather than modifying the prototype of all jobs.

**Comment by chriso** [comment]
Are you still having any trouble?

**Comment by kclay** [comment]
I was but just changed the way I'm creating the based methods, the problem was adding new methods to the extended Job would loose its scope since in process_worker.js a new Job instance is creating passing along a select number of functions (in the createInstance function).So when this happens the scope was being lost when calling "this."
