### ISSUE TITLE
Quiet job completion for .scrape()?

### ISSUE THREAD

**Issue by derekdr** [node-js-libs/node.io#35]
So:

I'm using .scrape() within another node.js application and the fact that node.io makes a hard kill after job completion is becoming a problem. After I call .scrape() and the job is completed it also kills my node.js server after outputting the job status.

Is there a way around this?

Also: I am aware that node.io is primarily a console application meant to be running on it's own; but it's just so sexy!

**Comment by blup** [comment]
Doesnt "-s, --silent (Hide console status messages)" work for you?

**Comment by derekdr** [comment]
Even if I didn't run the code from a separate node process started with the `node *.js` command (without node.io options that is) node.io would still kill the process.

'quiet' might not be the most excellent choice of words, what I'm really asking for is a 'void' option for jobs. Or actually, just not shutting down the node.io (or node) process after a job is done.

**Comment by chriso** [comment]
Hey, you can use the `nodeio.start()` method defined [here](https://github.com/chriso/node.io/blob/master/lib/node.io/processor.js#L41-54). Here's an example:

``` javascript
var nodeio = require('node.io');

var options = {};

var myjob = new nodeio.Job(options, {
    input: [1,2,3],
    run: function (num) {
        this.emit(num * 2);
    }
});

nodeio.start(myjob, function (err, output) {
    console.log(output); //[4,5,6]
}, true);
```

The `scrape()` is just a convenience method which creates a job with options `timeout:10, auto_retry:true`. You should have a look at [this page](https://github.com/chriso/node.io/wiki/Scraping) to see how to create more powerful scraping jobs

**Comment by derekdr** [comment]
Thanks! Just what I needed!
