### ISSUE TITLE
Local instalation?

### ISSUE THREAD

**Issue by demian85** [node-js-libs/node.io#37]
I don't get it, how can I use this module inside my own module without having to export a job as a module?? 
Global install does not work because require('node.io') breaks.
And in case that works, how can I start a job? is there any undocumented method to start a job?

**Comment by chriso** [comment]
Hey, you can use the currently undocumented `nodeio.start()` method defined [here](https://github.com/chriso/node.io/blob/master/lib/node.io/processor.js#L41-54). Here's an example:

``` javascript
var nodeio = require('node.io');

var options = {};

var myjob = new nodeio.Job(options, {
    input: [1,2,3],
    run: function (num) {
        this.emit(num * 2);
    }
});

nodeio.start(myjob, function (err, output) {
    console.log(output); //[4,5,6]
}, true);
```

Also note that `nodeio.start()` can take a path to a job as the first argument, e.g. `nodeio.start('/path/to/job', callback, capture_output);`

`require('node.io');` will work if node.io is installed locally or globally - if `require()` fails to find node.io, check `require.paths` vs. the installation dir or try installing it again.
