### ISSUE TITLE
Installation documentation

### ISSUE THREAD

**Issue by pbowyer** [node-js-libs/node.io#38]
As a new nodejs user, the global installation of node.io has been confusing, as I've had to install node.io globally and locally.

It appears by default (and design) that global installations are not in the path - this link https://github.com/isaacs/npm/issues/775#issuecomment-1389398 makes it clear this is intended (via http://stackoverflow.com/questions/6159552/problem-running-jobs-with-node-io/6415110#6415110).

I appreciate that you have a different view on the subject, so could you add steps to your installation page to explain what needs changing to the path and why, as the link above implies it's a bad idea to do?

Many thanks!

**Comment by chriso** [comment]
Apologies - pre-NPMv1, global node modules were installed in the path. I've looked at how some other popular projects handle it and made some [changes](https://github.com/chriso/node.io/commit/ea1b22f3cad87aa9a05567fc886a78df1d9f3ba1) in `0.3.6` - this should fix any issues you're having.

**Comment by chriso** [comment]
Once again, let me know if you need any more help ;)
