### ISSUE TITLE
How does skip work?

### ISSUE THREAD

**Issue by devjones** [node-js-libs/node.io#39]
I'm trying to ask node.io to skip a url that was piped in from a file since it return a 404 error. I tried the following but the code continued past the this.skip() and as a result failed on the subsequent selector processing.

   16         this.getHtml(url, function (err, $) {
   17             //Handle any request / parsing errors
   18             if (err) {
   19                 this.skip();
   20                 console.log(err); 
   21                 if (err == '404') {
   22                     console.log('skipping');
   23                     this.skip(); //<<----It's not skipping to the next url from stdin
   24                 }
   25                 else {
   26                     this.exit(err);
   27                 }
   28             }
   .....................

**Comment by devjones** [comment]
To anyone with the same issue, it appears you need to call:

return this.skip();

to actually skip the scraping for the current page.  This is a bit different from emit, where you only need to do :

this.emit(data);

Can be a bit tricky.  I'd recommend using similar syntax for both skip and emit to prevent confusion.

**Comment by chriso** [comment]
You don't need to `return this.skip()` to get the correct behaviour. What did you have outside of `if (err) { .. }` ? You may have been calling `this.skip()` and then evaluating something else, whereas `return this.skip()` returned immediately.

This example works as expected:

_test.js_

``` javascript
var nodeio = require('node.io');

exports.job = new nodeio.Job({timeout: 10, autoretry: true}, {
    input: [
        'http://www.google.com/'
      , 'http://www.google.com/saidfasdfkhlasdjkfhl'
      , 'http://www.google.com/'
      , 'http://www.google.com/8s7dafasdlfhk3lajhlkjh'
    ],
    run: function (url) {
        this.getHtml(url, function (err) {
            if (err == 404) {
                this.skip();
            } else {
                this.emit(url);
            }
        });
    }
});
```

``` bash
$ io test.js
http://www.google.com/
http://www.google.com/
OK: Job complete
```

**Comment by tarun1793** [comment]
Facing the same problem, skip doesnt iterate over the next element in input array.
Works in run, but not in @post or @get, and yes, using a fat arrow function for @post, whereas @emit works

**Comment by chriso** [comment]
@tarun1793 can you post a snippet of your scraping job? If you change `getHtml` to `get` in the example above it still works as expected
