### ISSUE TITLE
Add "delay" option to pause between calls to run()

### ISSUE THREAD

**Issue by odbol** [node-js-libs/node.io#44]
This is a great framework, very easy to use! I have one suggestion: a very important part of scraping (especially with APIs) is not clobbering the server with hundreds of requests at once. Many APIs will ban/block you if you make too many requests in a small time period. For instance, the Wikitravel API requires that you not make more than one request per 30 seconds. 

I suggest adding an Job option called "delay", in which you can specify the amount of time to wait before launching the next thread. That's pretty much the only thing that's missing. Thanks!

**Comment by chriso** [comment]
Hey thanks. You can use the undocumented `wait` option (defined [here](https://github.com/chriso/node.io/blob/master/lib/node.io/process_worker.js#L157-161)) along with the `max` option to limit the number of concurrent requests. It's also trivial to wrap your emit/skip/etc in a `setTimeout` if you need more fine-grained control

**Comment by odbol** [comment]
Thanks! Now documented!

It didn't quite fit for me since I don't always want to pause during a skip() so I took your advice and used setTimeout(). Will post that code soon...
