### ISSUE TITLE
installation error

### ISSUE THREAD

**Issue by tayknight** [node-js-libs/node.io#45]
node v0.4.10
npm 1.0.22

Error (from a local install or -g) is:

> contextify@0.0.3 preinstall /home/will/sources/nfl/node_modules/node.io/node_modules/jsdom/node_modules/contextify
> node-waf clean || true; node-waf configure build

sh: node-waf: not found
sh: node-waf: not found
npm ERR! error installing contextify@0.0.3 Error: contextify@0.0.3 preinstall: `node-waf clean || true; node-waf configure build`
npm ERR! error installing contextify@0.0.3 `sh "-c" "node-waf clean || true; node-waf configure build"` failed with 127
npm ERR! error installing contextify@0.0.3     at ChildProcess.<anonymous> (/usr/lib/node_modules/npm/lib/utils/exec.js:49:20)
npm ERR! error installing contextify@0.0.3     at ChildProcess.emit (events.js:67:17)
npm ERR! error installing contextify@0.0.3     at ChildProcess.onexit (child_process.js:192:12)
npm ERR! error installing jsdom@0.2.3 Error: contextify@0.0.3 preinstall: `node-waf clean || true; node-waf configure build`
npm ERR! error installing jsdom@0.2.3 `sh "-c" "node-waf clean || true; node-waf configure build"` failed with 127
npm ERR! error installing jsdom@0.2.3     at ChildProcess.<anonymous> (/usr/lib/node_modules/npm/lib/utils/exec.js:49:20)
npm ERR! error installing jsdom@0.2.3     at ChildProcess.emit (events.js:67:17)
npm ERR! error installing jsdom@0.2.3     at ChildProcess.onexit (child_process.js:192:12)
npm ERR! error installing node.io@0.3.6 Error: contextify@0.0.3 preinstall: `node-waf clean || true; node-waf configure build`
npm ERR! error installing node.io@0.3.6 `sh "-c" "node-waf clean || true; node-waf configure build"` failed with 127
npm ERR! error installing node.io@0.3.6     at ChildProcess.<anonymous> (/usr/lib/node_modules/npm/lib/utils/exec.js:49:20)
npm ERR! error installing node.io@0.3.6     at ChildProcess.emit (events.js:67:17)
npm ERR! error installing node.io@0.3.6     at ChildProcess.onexit (child_process.js:192:12)
npm ERR! contextify@0.0.3 preinstall: `node-waf clean || true; node-waf configure build`
npm ERR! `sh "-c" "node-waf clean || true; node-waf configure build"` failed with 127
npm ERR!
npm ERR! Failed at the contextify@0.0.3 preinstall script.
npm ERR! This is most likely a problem with the contextify package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-waf clean || true; node-waf configure build
npm ERR! You can get their info via:
npm ERR!     npm owner ls contextify
npm ERR! There is likely additional logging output above.
npm ERR!
npm ERR! System Linux 2.6.39.1-linode34
npm ERR! command "node" "/usr/bin/npm" "install" "node.io"
npm ERR! cwd /home/will/sources/nfl/node_modules
npm ERR! node -v v0.4.10
npm ERR! npm -v 1.0.22
npm ERR!
npm ERR! Additional logging details can be found in:
npm ERR!     /home/will/sources/nfl/node_modules/npm-debug.log
npm not ok

Any ideas? Thanks.

**Comment by chriso** [comment]
Looks like your problem is `sh: node-waf: not found`.

What does `which node-waf` say?

Are you running npm with `sudo`?

**Comment by tayknight** [comment]
which node-waf  returns nothing, either regular user or sudo.

**Comment by chriso** [comment]
You may have to reinstall node - node-waf should have been installed at the same time. Which version of node are you using?

**Comment by tayknight** [comment]
node v0.4.10
npm 1.0.22

**Comment by chriso** [comment]
Yeah I'd say reinstall - node-waf should definitely be there.

**Comment by tayknight** [comment]
Re-installation worked. Thanks for the quick help.
