### ISSUE TITLE
issue running a node.io script in a cron

### ISSUE THREAD

**Issue by sotonin** [node-js-libs/node.io#5]
i want to kick off a script in a cron. the script works fine if manually run. but from the cron the output i get is this...

/bin/sh: node.io: not found

im using the plain old user crontab -e to setup the cron, so it should run it as my standard user

any ideas?

the command im using is something like this
*/1 \* \* \* \* node.io /home/myuname/code/project/import.js >> /home/myuname/code/project/import_log.log 2>&1

**Comment by chriso** [comment]
Cron jobs need to have the full path of node.io specified - I think it's `/usr/local/bin/node.io` or maybe `/usr/bin/node.io`.

I'd also recommend wrapping the command with `nohup` and `&` to make node.io more persistent (see: [http://en.wikipedia.org/wiki/Nohup](http://en.wikipedia.org/wiki/Nohup)). Also you can use `&>` to redirect both stdout and stderr to import_log

Try this:

```
*/1 * * * * /usr/bin/nohup /usr/local/bin/node.io /home/myuname/code/project/import.js &> /home/myuname/code/project/import_log.log &
```

The other thing you could try is putting the following line into _/home/myuname/code/project/import.sh_

```
nohup node.io import &> import_log.log &
```

..and then in your crontab put:

```
*/1 * * * * /bin/sh /home/myuname/code/project/import.sh
```

**Comment by chriso** [comment]
Let me know if it doesn't work

**Comment by sotonin** [comment]
Hmm. i've looked at both /usr/local/bin/node.io and /usr/bin/node.io and node.io is at neither location. very bizarre. i'll try your .sh suggestion

**Comment by sotonin** [comment]
unfortunately the same issue with the sh method

import.sh: 1: node.io: not found

:(

**Comment by chriso** [comment]
Running `$ which node.io` should give you the full path of node.io

**Comment by sotonin** [comment]
OK. we're getting closer now. after putting the full path in the .sh now it logs this

/usr/bin/env: node: No such file or directory

**Comment by chriso** [comment]
Open up the actual `node.io` file in an editor and change the first line from

```
#!/usr/bin/env node
```

..to:

```
#!/usr/bin/env /usr/local/bin/node
```

..where /usr/local/bin/node is the path to your node app

**Comment by sotonin** [comment]
OK. i've pretty much blown away everything i've done and tried to start fresh with node and node.io

Somehow now i can't even get it to work the normal way (not in a cron).... the same old js scripts that used to work now give this.

ERROR: Failed to load job "import.js". Node.io accepts CoffeeScript and JS modules (.js/.coffee).

ive tried node v0.3.1 v0.3.2 and v0.3.3 all seem to behave the same. i was using v0.3.1 earlier so this is very odd

**Comment by chriso** [comment]
Reinstall node.io with `npm install node.io`

Download [this file](https://gist.github.com/raw/765758/6a8ef30033531ca60042348a87c0d5d4d9eea01d/gistfile1.js) and save it as helloworld.js, and then in the same directory run `node.io -s helloworld`

Does it output `Hello World!` ?

**Comment by sotonin** [comment]
I got it working. It appears the reason it gave the ERROR: Failed to load job "import.js". Node.io accepts CoffeeScript and JS modules (.js/.coffee). is because i had forgotten to install some dependencies after reinstalling node

after using npm to install the required libraries it went away. not sure if thats a bug or not, as the error message is a little confusing.

All is well now. my cron appears to be working correctly now after the full reinstall

**Comment by chriso** [comment]
Hmm very strange. What node version were you going from => to? and do you know which dependencies were playing up? 

Since installation with npm is the only way to install node.io and npm installs all dependencies, there's no point checking whether they are installed or not on each node.io run. It seems like it could be a bug with npm/node..

**Comment by sotonin** [comment]
The dependency that bugged it up to give that message was "mailer" npm install mailer i believe. Obviously this is not a dependency of node.io just a require() i had in my .js file i was trying to run with node.io. After i installed that it recognized it as a js just fine. Been using 0.3.3 mostly. back and forth between 0.3.1 0.3.2 and 0.3.3 just trying to get things to play nice. using 0.3.3 right now successfully

**Comment by chriso** [comment]
Ah I see - when node.io require()'s the job it throws the same error when the job isn't found and/or when it doesn't compile properly. I've updated the error message to be a bit less ambiguous - thanks for your help.
