### ISSUE TITLE
$ object catching errors

### ISSUE THREAD

**Issue by donl** [node-js-libs/node.io#52]
What is the recommended way to catch or prevent errors from throwing when scraping using the $ object?

This is the type of error I am getting:

/usr/local/lib/node_modules/node.io/lib/node.io/dom.js:25
        throw new Error("No elements matching '" + selector + "'");
              ^
Error: No elements matching 'div.foo p'

Somewhat related -- if the $ selection only returns one result, .each fails.

Suggestions on how I should best handle these edge cases?

**Comment by frederickcook** [comment]
See https://github.com/chriso/node.io/pull/56 regarding errors.

Regarding breaking .each, in jQuery, if no element is found with a given selector, [] is returned, a single element returns [element], and multiple returns [element1, element2]. Perhaps that would be a better convention? That would break a lot of code, though.

**Comment by chriso** [comment]
You can catch the errors with simple `try ... catch` or with the new third argument to the `$` object (thanks to @frederickcook).

The `each` issue with single vs. multiple items is covered [here](https://github.com/chriso/node.io/issues/34). The workaround is to either use jquery/jsdom or to remove [these lines](https://github.com/chriso/node.io/blob/master/lib/node.io/dom.js#L30-32) in your own build.
