### ISSUE TITLE
Scrapping stops the server

### ISSUE THREAD

**Issue by ladariha** [node-js-libs/node.io#55]
Hi,
maybe I'm doing something wrong, but I have simple function that handles request. It's just copy&paste of your example. It works fine, it prints all titles. However after that the console says "OK: Job complete" and the server is stopped, without any warning. Am I doing something wrong?

Code:
function index(response, request){

```
require('node.io').scrape(function() {
    this.getHtml('http://www.reddit.com/', function(err, $) {
        var stories = [];
        $('a.title').each(function(title) {
            stories.push(title.text);
        });
        this.emit(stories);
    });
});
```

**Comment by derekdr** [comment]
This might help you:
https://github.com/chriso/node.io/issues/35

**Comment by ladariha** [comment]
Thanks a lot, that's what I needed.
