### ISSUE TITLE
CoffeeScript jobs can't be used with command line options which require 'extend'

### ISSUE THREAD

**Issue by airhorns** [node-js-libs/node.io#57]
An example of the error:

```
hornairs@bishop:~/Code/busters (master *)$ cat jobs/hello.coffee 
nodeio = require 'node.io'
class Hello extends nodeio.JobClass
    input: ['']
    run: (num) -> @emit 'Hello World!'

@class = Hello
@job = new Hello()
```

```
hornairs@bishop:~/Code/busters (master *)$ node.io --debug jobs/hello.coffee 
DEBUG: Compiling jobs/hello.coffee => hello_compiled.js
DEBUG: Running 1 worker..
DEBUG: Writing to STDOUT
Hello World!
OK: Job complete
```

```
hornairs@bishop:~/Code/busters (master *)$ node.io --debug -i input.txt jobs/hello.coffee 
DEBUG: Compiling jobs/hello.coffee => hello_compiled.js

/usr/local/lib/node_modules/node.io/lib/node.io/processor.js:241
        job_obj = job_obj.extend(options.extend.options || {}, options.extend.
                          ^
TypeError: Object #<Hello> has no method 'extend'
    at [object Object].processJob (/usr/local/lib/node_modules/node.io/lib/node.io/processor.js:241:27)
    at /usr/local/lib/node_modules/node.io/lib/node.io/processor.js:328:30
```

Seems that the processing code expects all jobs to have an `extend` method so it can use it here: https://github.com/chriso/node.io/blob/master/lib/node.io/processor.js#L241, but CoffeeScript jobs don't end up with `extend`. 

CoffeeScript jobs extend (using the CoffeeScript class system) the `JobClass` property, as opposed to calling the `Job` function. `Job.extend` is defined in that `Job()` function (https://github.com/chriso/node.io/blob/master/lib/node.io/job.js#L106). `JobClass` never gets extend, so the processing code errors when it calls it. 

I think `extend` is in there because of the `JobClass` getter which returns a new object each time (so the prototype can't be mangled). Each `Job()` call operates on an effectively different `JobClass`, so the `extend` function body closes over the `JobClass` it's defined on. Maybe the solution to this is to define `extend` on the prototype and then bind it in the `Job()` function?

This is similar to #17 I believe, but I couldn't reproduce either.

**Comment by chriso** [comment]
Try piping the input in rather than relying on `-i` (buggy):

_hello.coffee_

``` coffeescript
nodeio = require 'node.io'
class Hello extends nodeio.JobClass
    run: (name) -> @emit 'Hello ' + name

@class = Hello
@job = new Hello()
```

Run with

``` bash
$ echo "chris" | node.io hello
```

or 

``` bash
$ node.io hello < names.txt
```
