### ISSUE TITLE
Redirect Issues

### ISSUE THREAD

**Issue by donl** [node-js-libs/node.io#58]
I noticed a few issues with regards to HTTP redirects-

1)  Cookies that are set for the initial request are not sent to the server on the redirect requests (when redirects are enabled).
2)  Set-Cookie headers received after automatically following a redirect are not returned with the .get/.getHtml response headers
3)  When setting redirect=0, I am able to catch the redirect by detecting 'err' being set in the callback, however again the headers for the callback are not being set (such as Location).

Thanks!

**Comment by chriso** [comment]
Thanks for finding these - I will likely port the entire request process over to use [this library](https://github.com/mikeal/request) in the near future.

**Comment by chriso** [comment]
The request process now uses [mikeal/request](https://github.com/mikeal/request) so these issues should be fixed.
