### ISSUE TITLE
Documentation for spiders and complex input functions

### ISSUE THREAD

**Issue by Torkn** [node-js-libs/node.io#59]
I'm struggling to implement a spider in node.io - basically it should start at a starting URL, follow and fetch links matching some criteria, and ultimately fetch and process links matching another criteria.

Example: A local council may publish development applications, organised by date.  Within each date page, there is a list of individual applications.  Within the page for each individual application, there is a bunch of useful data fields, like address and type of construction (extension/pool/garage etc).  Or a shop may have products organised by a hierarchy of categories, only some of which you want to spider.

I assume that the way this should be constructed is that the input method should generate a series of URLs (via spidering) and then the run method should fetch and scrape those URLs.

If I manually construct a list of URLs and supply that as the input method, then I already have a run method that will fetch the URL via this.getHtml and emit the appropriate scraped information.

But I can't manage to write a suitable function for the input method that spiders the original site to find all the development applications.  Nor can I find any documentation or examples that involve an input function that fetches URLs and parses/scrapes the HTML in order to produce the input for the run method.

Can you use this.getHTML in an input function?

Can you use this.emit in an input function to send input to the run method? (It seems to terminate the run method, so I guess no).

How does the input method signal that there is no more input?

How do you manage timeouts and rate limiting, when the total job may take a very long time?

Anyway, I am submitting this as an issue, that there appears to be no documentation for the construction of spiders.

**Comment by chriso** [comment]
I agree, the documentation could be better, but I haven't got enough free time to write up the extensive docs you're looking for. I'd suggest having a good read through [what's there already](https://github.com/chriso/node.io/wiki) - it covers the basics regarding input/output and some basic scraping. The only advice I can give is to split the tasks down into the smallest possible units. In the example you've provided, I'd probably write 3 or 4 separate scraping jobs that pull all of the URLs from a page, and then I'd pipe the output from each into the input of another, e.g. `echo "starturl.com" | node.io job1 | node.io job2`. If you follow this recipe then you don't have to worry about input or output (as STDIN/STDOUT is the default).

Run `npm install node.io` in a directory and then try this as a boilerplate:

``` javascript
var nodeio = require('node.io');
exports.job = new nodeio.Job({ max: 10, timeout: 10 }, {
    run: function (url) {
        this.getHtml(url, function (err, $) {
             //Use $ to find whatever you want to scrape
             //If you're done, use this.emit()
             //If you want to skip this page, use this.skip()
             //If you need to dynamically add more input, use this.add(url)
        });
    }
});
```

Again, read [the wiki](https://github.com/chriso/node.io/wiki), it has a lot of useful information.

**Comment by st3phan** [comment]
How would this work if I want to run my script from within another script? I can't seem to figure out how to use the output from job1 as input from job 2. Here's my code:

``` javascript

    var options = { timeout: 10 };

    var job1 = new nodeio.Job({
        input: ['www.domain.tld'],
        run: function(url) {
            var self = this;
            this.getHtml(url, function (err, $) {
                if (err) throw err;

                var urls = [];
                $('#links li').each(function(li) {
                    var url = $('a', li).attribs.href;
                    urls.push(url);
                });

                self.emit(urls);
            });
        }
    });

    var job2 = new nodeio.Job({
        // input: ???,
        run: function(url) {
            var self = this;
            // save to database
            self.emit(url);
        }
    });

    setInterval(function() {
        nodeio.start(job1, options, function(err, output) {
            // How do I use output as input for following job
            nodeio.start(job2, options, function(err, output) {
                console.log(output);
            });
        }, true);
    }, 10000)
```

**Comment by chriso** [comment]
@st3phan it's primarily designed so that io can be piped between separate scripts however you can use 

``` javascript
var nodeio = require('node.io');

var options = {
    timeout: 10
  , silent: true
};

var job1 = new nodeio.Job({
    input: [ 1, 2, 3 ],
    run: function (num) {
        this.emit(num * 2);
    }
});

var job2 = new nodeio.Job({
    run: function (num) {
        this.emit(num * 2);
    }
});

nodeio.start(job1, options, function (err, output) {
    job2.input = output;
    //The following undocumented call is used to parse the input value
    //and convert it into a function which node.io can use:
    job2.handleSpecialIO();
    nodeio.start(job2, options, function (err) {
        console.log(output); // => [4, 8, 12 ]
    }, true);
}, true);
```

**Comment by st3phan** [comment]
Great, thank you @chriso !

**Comment by davidlevy** [comment]
Should be     

nodeio.start(job2, options, function (err, output) {
        console.log(output); // => [4, 8, 12 ]
    }, true);

Thanks !

**Comment by VAS** [comment]
@chriso : your example doesn't compile correctly. Gives: Cannot read property 'options' of undefined.
