### ISSUE TITLE
Missing something?

### ISSUE THREAD

**Issue by hemanth** [node-js-libs/node.io#6]
```
> echo "mastercard.com" | node.io pagerank    
ERROR: Failed to load job "pagerank". Please check that the job exists and compiles correctly.
```

**Comment by chriso** [comment]
What version of node are you using and what does `ls ~/.node_modules` say ? 

The built-in modules from [here](https://github.com/chriso/node.io/tree/master/builtin) should be installed to `~/.node_modules`. I have a feeling that new versions of node may use `~/.node_libraries` instead (I'm using v0.2.6 so can't confirm)..

If all else fails, download [pagerank.coffee](https://github.com/chriso/node.io/raw/master/builtin/pagerank.coffee) and put it in your cwd.

Happy scraping!

**Comment by hemanth** [comment]
```
> ls ~/.node_modules
digest.js      eval.js      resolve.js   word_count.js
duplicates.js  pagerank.js  validate.js

> node --version
v0.2.6
```

With pagerank.coffee in pwd :

```
node.js:63
    throw e;
    ^
```

ReferenceError: strord is not defined
    at [object Object].run (/tmp/node.io/examples/pagerank_compiled.js:28:27)
    at EventEmitter.<anonymous> (/usr/local/lib/node/.npm/node.io/0.2.1-15/package/lib/node.io/process_worker.js:254:28)
    at EventEmitter.emit (events:28:17)
    at Array.<anonymous> (/usr/local/lib/node/.npm/node.io/0.2.1-15/package/lib/node.io/process_worker.js:106:24)
    at EventEmitter._tickCallback (node.js:55:22)
    at node.js:773:9

**Comment by chriso** [comment]
strord is definitely defined in the file - something strange is going on. A reinstall will probably fix it -> reinstall coffee as well.

```
npm install coffee && npm install node.io
```

Your pagerank.js file should look like this:

```
(function() {
  var Pagerank, UsageDetails, nodeio, options, usage;
  var __hasProp = Object.prototype.hasOwnProperty, __extends = function(child, parent) {
    for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; }
    function ctor() { this.constructor = child; }
    ctor.prototype = parent.prototype;
    child.prototype = new ctor;
    child.__super__ = parent.prototype;
    return child;
  }, __bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; };
  usage = 'This module checks a URL\'s Google pagerank (rate limits apply)\n\n   1. To find the pagerank of a URL:\n       $ echo "mastercard.com" | node.io -s pagerank    \n          => mastercard.com,7';
  nodeio = require('node.io');
  options = {
    timeout: 10,
    retries: 3
  };
  Pagerank = (function() {
    function Pagerank() {
      Pagerank.__super__.constructor.apply(this, arguments);
    }
    __extends(Pagerank, nodeio.JobClass);
    Pagerank.prototype.run = function(input) {
      var ch, url;
      url = input;
      if (url.indexOf('http://') === -1) {
        url = 'http://' + url;
      }
      ch = '6' + GoogleCH(strord('info:' + url));
      return this.get('http://www.google.com/search?client=navclient-auto&ch=' + ch + '&features=Rank&q=info:' + encodeURIComponent(url), __bind(function(err, data) {
        var match;
        if (err != null) {
          return this.retry();
        }
        if (match = data.match(/Rank_1:1:(10|[0-9])/)) {
          return this.emit(input + ',' + match[1]);
        } else {
          return this.emit(input + ',');
        }
      }, this));
    };
    return Pagerank;
  })();
  UsageDetails = (function() {
    function UsageDetails() {
      UsageDetails.__super__.constructor.apply(this, arguments);
    }
    __extends(UsageDetails, nodeio.JobClass);
    UsageDetails.prototype.input = function() {
      this.status(usage);
      return this.exit();
    };
    return UsageDetails;
  })();
  this["class"] = Pagerank;
  this.job = {
    pagerank: new Pagerank(options),
    help: new UsageDetails()
  };

// BEING CODE FOR GENERATING GOOGLE PAGERANK CHECKSUMS
//----------------------------------------------------------------------------------------------
function zF(a,b) {
    var z = parseInt(80000000,16);
    if (z & a) {
        a = a>>1;
        a &=~z;
        a |= 0x40000000;
        a = a>>(b-1);
    } else {
        a = a>>b;
    }
    return(a);
}
function mix(a,b,c) {
    a-=b; a-=c; a^=(zF(c,13));
    b-=c; b-=a; b^=(a<<8);
    c-=a; c-=b; c^=(zF(b,13));
    a-=b; a-=c; a^=(zF(c,12));
    b-=c; b-=a; b^=(a<<16);
    c-=a; c-=b; c^=(zF(b,5));
    a-=b; a-=c; a^=(zF(c,3));
    b-=c; b-=a; b^=(a<<10);
    c-=a; c-=b; c^=(zF(b,15));
    return (new Array((a),(b),(c)));
}
function GoogleCH(url,length) {
    if(arguments.length == 1) length=url.length;
    var a=0x9E3779B9, b=0x9E3779B9, c=0xE6359A60, k=0, len=length, mx=new Array();
    while(len>=12) {
        a+=(url[k+0]+(url[k+1]<<8)+(url[k+2]<<16)+(url[k+3]<<24));
        b+=(url[k+4]+(url[k+5]<<8)+(url[k+6]<<16)+(url[k+7]<<24));
        c+=(url[k+8]+(url[k+9]<<8)+(url[k+10]<<16)+(url[k+11]<<24));
        mx=mix(a,b,c);
        a=mx[0]; b=mx[1]; c=mx[2];
        k+=12; len-=12;
    }
    c+=length;
    switch(len) {
        case 11: c+=url[k+10]<<24;
        case 10: c+=url[k+9]<<16;
        case 9:c+=url[k+8]<<8;
        case 8:b+=(url[k+7]<<24);
        case 7:b+=(url[k+6]<<16);
        case 6:b+=(url[k+5]<<8);
        case 5:b+=(url[k+4]);
        case 4:a+=(url[k+3]<<24);
        case 3:a+=(url[k+2]<<16);
        case 2:a+=(url[k+1]<<8);
        case 1:a+=(url[k+0]);
    }
    mx=mix(a,b,c);
    if(mx[2]<0) {
        return(0x100000000+mx[2]);
    } else {
        return(mx[2]);
    }
}
function strord(string) {
    var result=new Array();
    for(i=0;i<string.length;i++){
        result[i]=string[i].charCodeAt(0);
    }
    return(result);
}
//----------------------------------------------------------------------------------------------
;
}).call(this);
```

**Comment by hemanth** [comment]
>  npm install coffee

```
npm info it worked if it ends with ok
npm info using npm@0.2.15
npm info using node@v0.2.6
npm ERR! Error: 404 Not Found: coffee
npm ERR!     at IncomingMessage.<anonymous
```

(/usr/local/lib/node/.npm/npm/0.2.15/package/lib/utils/registry/request.js:150:16)
    npm ERR!     at IncomingMessage.emit (events:48:20)
    npm ERR!     at HTTPParser.onMessageComplete (http:107:23)
    npm ERR!     at Client.onData [as ondata](http:854:27)
    npm ERR!     at IOWatcher.callback (net:494:29)
    npm ERR!     at node.js:773:9
    npm ERR! 404 
    npm ERR! 404 Looks like 'coffee' is not in the npm registry.
    npm ERR! 404 You should bug the author to publish it.
    npm ERR! 404 Note that you can also install from a tarball or local folder.
    npm ERR! 404
    npm not ok

**Comment by chriso** [comment]
Sorry - `npm install coffeescript`

It's automatically installed with `npm install node.io` though.

**Comment by hemanth** [comment]
Sorry again, i think i have screwed up very badly :(
  npm info it worked if it ends with ok
  npm info using npm@0.2.15
  npm info using node@v0.2.6
  npm ERR! Error: 404 Not Found: coffeescript
  npm ERR!     at IncomingMessage.<anonymous
(/usr/local/lib/node/.npm/npm/0.2.15/package/lib/utils/registry/request.js:150:16) 
  npm ERR!     at IncomingMessage.emit (events:48:20)
  npm ERR!     at HTTPParser.onMessageComplete (http:107:23)
  npm ERR!     at Client.onData [as ondata](http:854:27)
  npm ERR!     at IOWatcher.callback (net:494:29)
  npm ERR!     at node.js:773:9
  npm ERR! 404 
  npm ERR! 404 Looks like 'coffeescript' is not in the npm registry.
  npm ERR! 404 You should bug the author to publish it.
  npm ERR! 404 Note that you can also install from a tarball or local folder.
  npm ERR! 404
  npm not ok

**Comment by chriso** [comment]
Not your fault - it's just an ambiguous npm package name - it's `npm install coffee-script`. Try that, then run `npm install node.io` and then run `coffee -v && node.io -v` - it should say:

```
CoffeeScript version 1.0.0
INFO: v0.2.1-18
```

Next try running `echo "mastercard.com" | node.io -s pagerank` - it should say:

```
mastercard.com,8
```

**Comment by hemanth** [comment]
Worked! :) Kool! /me now looks for real parsing tricks :)

**Comment by chriso** [comment]
Cool - let me know if you need any other help.

**Comment by hemanth** [comment]
Sure - Will get productive with this first :)

**Comment by sergioeugenio** [comment]
Thanks chriso, a great help.
