### ISSUE TITLE
ISO-8859-1 Files and Umlauts

### ISSUE THREAD

**Issue by macrauder** [node-js-libs/node.io#60]
Hi,

i have ISO-8859-1 html files that i try to scrapp with getHtml.
The scrapping works perfect but i didn't get the umlauts back in a way to work with it.
All umlaut are broken.
Is there a way to convert iso html files to utf.8 in front of the parsing process?
For test you can use http://liveticker.toyota-handball-bundesliga.de/spiel_001512000000000000000000000000000002021.html
the String Südmeier, Sören is interpreted as S�dmeier, S�ren..

Thx

**Comment by chriso** [comment]
Currently there's no support for encodings other than those supported by Node ([UTF8 or Binary](http://nodejs.org/docs/v0.5.4/api/http.html#request.setEncoding)). You can try setting the `encoding` option to _binary_ (see [this line](https://github.com/chriso/node.io/blob/master/lib/node.io/request.js#L322)) and then use the iconv library to interpret the ISO-8859-1 responses.

**Comment by gabrielstuff** [comment]
Hum, not sure I get it ? Are we suppose to get the correct character with node.io + v0.8.8 ?

I got `iso-8859-1` html scrap and it fails to retrieve correct character set.

Thanks !
