### ISSUE TITLE
Change Job Options at runtime

### ISSUE THREAD

**Issue by macrauder** [node-js-libs/node.io#61]
Hi,

i must change the wait option based on the result of the scapping.
That means i will change the "wait" option at runtim in the ouput phase.
Is this possible.

Thx Macrauder

**Comment by chriso** [comment]
Hi, you can use your own `setTimeout` wrapping `emit`, `skip`, etc. to emulate a wait call.

E.g.

``` javascript
var self = this;
setTimeout(function () { 
    self.emit(/* something */);
});
```

Have a look at [this identical issue](https://github.com/chriso/node.io/issues/44)
