### ISSUE TITLE
jsdom memory leak

### ISSUE THREAD

**Issue by macrauder** [node-js-libs/node.io#62]
hi,

i must use jsdom in node.io to scrapp a complex html site.
Unfortunatly jsdom is consuming after a few minutes the gigs of memory. I found the problem solution here
http://stackoverflow.com/questions/5718391/memory-leak-in-node-js-scraper
but didn't find the correct position in node.io to call 
window.close()
to fix the problem tmeporarily.
Can you give me a hint!

Thx Macrauder

Sample:

var nodeio = require('node.io'), options = {timeout: 10};
var scrapp_options = {
  jsdom: true, 
  wait: 2,
  timeout: 10
};
var job = new nodeio.Job(scrapp_options, {
    input: true,
    run: function (keyword) {
        this.getHtml('http://www.spiegel.de', function (err, $) {
            console.log($('.spTopThema h2').html());
            this.emit();
        });
    }
});
nodeio.start(job, options, function (err, output) {}, false);

**Comment by chriso** [comment]
I've exposed the window object in `node.io v0.3.9`. Call `this.window.close()` before calling `this.emit()`, `this.skip()`, etc.
