### ISSUE TITLE
Testing selectors

### ISSUE THREAD

**Issue by creativetags** [node-js-libs/node.io#63]
Hi

I'm trying to write a simple screen scrapper and I'm getting stuck over what should be simple selectors. Is there a simple way to quickly test if my selector is right? I'm thinking a firefox extension or something?

Thanks

Mark

**Comment by creativetags** [comment]
I think the problem is I'm selecting more than one element and so it's creating an array instead of an object.

**Comment by chriso** [comment]
If there's multiple items matching the selector, you can use `each()` to iterate over all of them. Have a look at the [API](https://github.com/chriso/node.io/wiki/API---CSS-Selectors-and-Traversal-methods) for some other helper methods.

As for finding the right selectors, you can use something like [SelectorGadget](http://www.selectorgadget.com/) although note that it might give you some strange pseudo-selectors (e.g. `nth-child`) which aren't supported by the default node.io selector engine. I just use Firefox or Chrome's _Inspect Element_ tool to figure out which selectors to use. If in doubt, `console.log` is your friend ;)

**Comment by creativetags** [comment]
Thanks Chris. Is there a full list of supported selectors? Can't seem to find it on the node-soupselect page.

**Comment by chriso** [comment]
It fully supports simple tag/class/id/attribute selectors, and nested versions of each:

``` javascript
$('a')
$('a.foo')
$('a#foo')
$('a#foo.bar')
$('a.foo.bar')
$('p a')
$('p.foo a.bar')
$('input[type=text]')
//etc
```

It also looks like there's some other attribute selectors [here](https://github.com/harryf/node-soupselect/blob/master/lib/soupselect.js#L33-46), although I haven't tested them.
