### ISSUE TITLE
Option to run output only when all input is consumed

### ISSUE THREAD

**Issue by Robdr** [node-js-libs/node.io#64]
I'm running a job pretty regularly which always makes few requests (it has about 5-10 lines of input in general). To minimize database impact it would be great if the the output method could only be run once after all the input is consumed.

**Comment by chriso** [comment]
There's a `complete()` method which is called at job completion. You can collect output each time `output()` is called and then handle in (or in your case, export to DB) in `complete()`. See this example which outputs `[2,4,6]`:

``` javascript
var nodeio = require('node.io')
  , output = []

exports.job = new nodeio.Job({}, {

    input: [1, 2, 3]
  , run: function (num) { return num * 2 }

    //Store output for later
  , output: function (elem) {
        output = output.concat(elem)
    }

    //complete() is used to add custom onComplete behaviour. The
    //callback is provided so that node.io knows when any (a)sync
    //behaviour is complete and it should continue
  , complete: function (callback) {
        console.log(output)
        callback()
    }

});
```
