### ISSUE TITLE
Cannot nest getHtml/postHtml

### ISSUE THREAD

**Issue by mhart** [node-js-libs/node.io#66]
The following job:

``` coffeescript

class TestJob extends nodeio.JobClass
  input: [0..5]
  run: (num) ->
    @get 'google.com', =>
      @getHtml 'google.com', =>
        @emit num
```

Results in:

```
$ node.io test
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
OK: Job complete
```

If `getHtml` is changed to `get`, then the job functions correctly:

``` coffeescript

class TestJob extends nodeio.JobClass
  input: [0..5]
  run: (num) ->
    @get 'google.com', =>
      @get 'google.com', =>
        @emit num
```

Results in:

```
$ node.io test
0
1
2
3
4
5
OK: Job complete
```

This seems to make it very difficult to do any parsing that requires a login form, or post, or anything similar.

Is this intended behaviour, or am I missing something completely?

**Comment by bebraw** [comment]
+1. It would be awesome to have this fixed.

**Comment by janarthananramar** [comment]
+1. It would be great if you can post some nested getHtml examples,  at the moment its not working.

**Comment by chriso** [comment]
@bebraw @maxgilander should be fixed now
