### ISSUE TITLE
wrong file permissions using output:

### ISSUE THREAD

**Issue by alexwall** [node-js-libs/node.io#68]
Hi Chris, 

using 

`output:  "my_file.txt"`

in a job, node.io will create the file with this file permissions for the my_file.txt 

```
 --w---x---
```

If I use `fs.writeFile` I got normal permissions for this file 

```
 -rw-r--r--
```

Any idea?

**Comment by chriso** [comment]
It was an octal vs decimal issue when setting write permissions. Fixed in `0.4.3`
