### ISSUE TITLE
ERROR: The job could not be found.

### ISSUE THREAD

**Issue by amih** [node-js-libs/node.io#71]
I just installed node.io and tried the first example in the wiki with debug on:
node.io --debug myjob.js

I get the following:

DEBUG: Attempting to load require('/home/ami/dev/scraping/myjob.js')
DEBUG: Failed to load require('/home/ami/dev/scraping/myjob.js') - not found
DEBUG: Attempting to load require('myjob.js')
DEBUG: Failed to load require('myjob.js') - not found
ERROR: The job could not be found.

I know the file myjob.js is in /home/ami/dev/scraping/myjob.js and it is the current directory.
node --version is v0.6.5

I searched for similar problems but found no solution,
Please help

**Comment by chriso** [comment]
There was a bug where it would report `not found` for _myjob.js_ when actually one of the modules `require()`'d inside that file could not be found.

It's probably a case of not being able to find a local copy of `node.io`. Try running `npm install node.io` in the same directory as _myjob.js_. If it doesn't work, the latest version should at least give you a more accurate error message.

**Comment by amih** [comment]
Thanks!
I did what you suggested and it still doesn't work, probably something with my setup... I hope it will be obvious to you - I'm clue less.

I ran `npm install node.io` in the same directory, here is the output:

> npm WARN cron@0.1.3 package.json: bugs['web'] should probably be bugs['url']
> npm WARN htmlparser@1.7.3 package.json: bugs['web'] should probably be bugs['url']
> npm WARN htmlparser@1.6.2 package.json: bugs['web'] should probably be bugs['url']
> 
> > contextify@0.0.6 preinstall /home/ami/node_modules/node.io/node_modules/jsdom/node_modules/contextify
> > node-waf clean || true; node-waf configure build
> 
> Nothing to clean (project not configured)
> Setting srcdir to                        : /home/ami/node_modules/node.io/node_modules/jsdom/node_modules/contextify 
> Setting blddir to                        : /home/ami/node_modules/node.io/node_modules/jsdom/node_modules/contextify/build 
> Checking for program g++ or c++          : /usr/bin/g++ 
> Checking for program cpp                 : /usr/bin/cpp 
> Checking for program ar                  : /usr/bin/ar 
> Checking for program ranlib              : /usr/bin/ranlib 
> Checking for g++                         : ok  
> Checking for node path                   : not found 
> Checking for node prefix                 : ok /usr/local 
> 'configure' finished successfully (0.785s)
> Waf: Entering directory `/home/ami/node_modules/node.io/node_modules/jsdom/node_modules/contextify/build'
> [1/2] cxx: src/contextify.cc -> build/Release/src/contextify_1.o
> [2/2] cxx_link: build/Release/src/contextify_1.o -> build/Release/contextify.node
> Waf: Leaving directory`/home/ami/node_modules/node.io/node_modules/jsdom/node_modules/contextify/build'
> 'build' finished successfully (3.435s)
> npm WARN prefer global node.io@0.4.5 should be installed with -g
> node.io@0.4.5 ../../node_modules/node.io 
> ├── jquery@1.6.3
> ├── request@2.2.9
> ├── coffee-script@1.1.3
> ├── htmlparser@1.7.3
> └── jsdom@0.2.10

Then I tried `ami@amihlaptop:~/dev/scraping$ node.io --debug myjob.js` again and got:

> DEBUG: Attempting to load require('/home/ami/dev/scraping/myjob.js')
> DEBUG: Running 1 worker..
> 
> node.js:201
>         throw e; // process.nextTick error, or 'error' event on first tick
>               ^
> TypeError: Cannot call method 'match' of undefined
>     at [object Object].doRequest (/home/ami/local/node/lib/node_modules/node.io/lib/node.io/request.js:222:19)
>     at [object Object].get (/home/ami/local/node/lib/node_modules/node.io/lib/node.io/request.js:53:10)
>     at [object Object].run (/home/ami/dev/scraping/myjob.js:6:14)
>     at EventEmitter.<anonymous> (/home/ami/local/node/lib/node_modules/node.io/lib/node.io/process_worker.js:253:28)
>     at EventEmitter.emit (events.js:64:17)
>     at Array.0 (/home/ami/local/node/lib/node_modules/node.io/lib/node.io/process_worker.js:113:24)
>     at EventEmitter._tickCallback (node.js:192:40)

This is the directory's content:

> ami@amihlaptop:~/dev/scraping$ ll
> total 12
> drwxrwxr-x  2 ami ami 4096 2011-12-06 15:59 ./
> drwxr-xr-x 17 ami ami 4096 2011-12-06 13:26 ../
> -rw-rw-r--  1 ami ami  334 2011-12-06 13:27 myjob.js

**Comment by chriso** [comment]
Sorry for the delay. Looks like you're calling `get/post/getHtml/postHtml` with incorrect arguments. Can you post your job or at least the line where you call one of those methods?

**Comment by amih** [comment]
OMG! I'm so stupid!
I ran the example without a required parameter - the url I want to scrape!!
Your comment helped - I did call the get function without a required parameter.

I just tested `node.io --debug myjob.js http://google.com` and it works perfectly.
Sorry to waste brain cycles...
Thanks anyway!

The job is from the tutorial:
```var nodeio = require('node.io');
exports.job = new nodeio.Job({
    input: false,
    run: function () {
        var url = this.options.args[0];
        this.get(url, function(err, data) {
            if (err) {
                this.exit(err);
            } else {
                this.emit(data);
            }
        });
    }
});

```
```

**Comment by chriso** [comment]
No probs :) let me know if you need any more help
