### ISSUE TITLE
"Error: require.paths is removed." when running node.io-web

### ISSUE THREAD

**Issue by danielhum** [node-js-libs/node.io#73]
hello,

I am unable to run the web interface. when I do `node.io-web -p 8080`, I get the error:
`Error: require.paths is removed. Use node_modules folders, or the NODE_PATH environment variable instead.
    at Function.<anonymous> (module.js:376:11)
    at Object.web (/usr/local/lib/node_modules/node.io/lib/node.io/interfaces/web.js:47:32)
    at Object.<anonymous> (/usr/local/lib/node_modules/node.io/bin/node.io-web:5:14)
    at Module._compile (module.js:432:26)
    at Object..js (module.js:450:10)
    at Module.load (module.js:351:31)
    at Function._load (module.js:310:12)
    at Array.0 (module.js:470:10)
    at EventEmitter._tickCallback (node.js:192:40)`

I have npm v1.1.0-beta-4 and node v0.6.6 installed, on OSX 10.6.8. I installed node.js using the installer on nodejs.org

It seems modules are getting installed at `/usr/local/lib/node_modules` for global or `./node_modules` (in the current project dir)

the wiki says to put jobs in `~/node_modules` which seems to no longer exist or be in use (I'm new to Node.js, correct me if I'm wrong).

a quick and dirty fix that worked was to manually set module_dir and remove the block involving require.paths, but is there a better way to fix this?

**Comment by chriso** [comment]
I hacked together the web interface over a year ago when the node API and way modules were handled were very different. I'll have to have a look at upgrading this at some stage though. `require.paths` was removed a few months ago and so the only solution is to specify the module dir at the command line or default to the current directory.

**Comment by snez** [comment]
+1

**Comment by crystalneth** [comment]
This is one of the first things mentioned under "getting started" and it's broken. Suggest at least removing it from the doc for now as it gives the impression something is terribly wrong when trying to "get started."

**Comment by chriso** [comment]
Agreed. It's removed for now
