### ISSUE TITLE
Asynchronous IO in output-function

### ISSUE THREAD

**Issue by Robdr** [node-js-libs/node.io#78]
Is there a way to manually indicate that the the output-function has completed? 

I'm currently doing some async writes to a database in the output function, but since there's is no way to indicate that the output function has completed it will terminate the job before the async output is completed.

**Comment by chriso** [comment]
You can use the `complete` method to add any (a)sync code you need executed on job completion, e.g. waiting for async output to complete.

From the [wiki](https://github.com/chriso/node.io/wiki/API-Job-Methods):

``` javascript
complete: function(callback) {
    console.log('Job complete.');
    callback();
}
```
