### ISSUE TITLE
Asserts fail silently?

### ISSUE THREAD

**Issue by astrofinch** [node-js-libs/node.io#8]
I tried reddit.coffee from the tutorial and didn't get any output.  For reference, here's the source code:

<pre>
nodeio = require('node.io')

titles = []
scores = []
output = []

class Reddit extends nodeio.JobClass
    input: false
    run: -> 
        @getHtml 'http://www.reddit.com/', (err, $, data) =>
            @exit err if err?

            $('a.title').each (a) -> titles.push a.text
            $('div.score.unvoted').each (div) -> scores.push div.rawtext

            @exit 'Title / score mismatch' if scores.length isnt titles.length

            for score, i in scores
                if score is '&bull;' then continue
                @assert(score).isInt()
                output.push '[' + score + '] ' + titles[i]

            @emit output

@class = Reddit
@job = new Reddit({timeout:10})
</pre>

After a bit of debugging, I realized that something had changed since the tutorial had been written so that div.rawtext was undefined.  This was triggering @assert(score).isInt() to fail so that threads would terminate without printing undefined.  However, there wasn't any sort of message that the assertion had failed, even when I ran things with the -g flag:

<pre>

john-laptop :: ~/tmp » node.io -g reddit.coffee                             1 ↵
INFO: Compiling /home/john/tmp/reddit.coffee
INFO: Running 1 worker..
DEBUG: GET http://www.reddit.com/
DEBUG: 200 http://www.reddit.com/
OK: Job complete
</pre>

Is there something I can do to see when an assert fails?

**Comment by chriso** [comment]
`if score is '•' then continue` should be `if score is '&bull;' then continue` - the assert() method throws an exception, so wrap it in a try...catch

**Comment by chriso** [comment]
it seems the entity `& bull ;` (no spaces) is being converted somewhere.. :)

**Comment by chriso** [comment]
another note, failures a fairly common occurrence when scraping large amounts of data - if a thread fails with assert, a 4xx or 5xx, etc, it automatically calls the fail() method if it's defined (see the bottom of [this page](https://github.com/chriso/node.io/wiki/Getting-Started) for more info)
