### ISSUE TITLE
Get javascript generated html

### ISSUE THREAD

**Issue by Charuru** [node-js-libs/node.io#80]
On a site I'm trying to scrape the html is generated by client side javascript.

Can I use node.io to scrape it or is that not supported. Thanks.

**Comment by chriso** [comment]
Set the `jsdom` [option](https://github.com/chriso/node.io/wiki/API---Job-Options) to `true` to enable the [jsdom](https://github.com/tmpvar/jsdom) parser. You may also need to set the `external_resources` option to true if the page you're scraping needs to load any `<script>` tags. After requesting the page you have access to the a `window` object and jQuery fn `$`. Have a look at [this code](https://github.com/chriso/node.io/blob/master/lib/node.io/dom.js#L59-72)

**Comment by discoverpost** [comment]
chriso, could you explain how the window object selects elements, and how the $ which appears to be undefined, comes into play?"

EDIT: nevermind, i didnt pass the $ in function(err,$){}

**Comment by chriso** [comment]
Great
