### ISSUE TITLE
Request setCookie and addCookie doesn't work

### ISSUE THREAD

**Issue by crackcomm** [node-js-libs/node.io#81]
Hey, here is my code:
https://gist.github.com/447a80e6104fae95bf92
Requested website is var_dump'ing cookie, result:
"The "sys" module is now called "util". It should have a similar interface.
cookie: NULL"

I was trying even this.setHeader('set-cookie', 'oko=1');

**Comment by chriso** [comment]
I can't replicate this. Cookie tests are passing and the following script outputs the expected.

**cookies.php**

``` php
<?php var_dump($_COOKIE);
```

**test.js**

``` javascript
var nodeio = require('node.io');

exports.job = new nodeio.Job({}, {
    input: false
  , run: function () {
        this.setCookie('foo', 'bar');
        this.get('http://localhost/cookies.php', function(err, data) {
            this.emit(data);
        });
    }
});
```

``` bash
~ $ node.io test   
array(1) {
  ["foo"]=>
  string(3) "bar"
}
```
