### ISSUE TITLE
Jobs that fail when memory runs out

### ISSUE THREAD

**Issue by ababushkin** [node-js-libs/node.io#82]
Currently when there is a long continuous job running (e.g. parsing a directory full of HTML files) nodeJS crashes even if very little information is stored in memory (e.g. an output file is written to a CSV file rather than stored in a JSON object).

Would be nice if there was a way to increase the memory limit, or perhaps some examples of how these sort of jobs can be run via the "nodejs" command instead of "node.io"?

**Comment by chriso** [comment]
You can also run a job using the method `nodeio.start(job, options, callback, capture_output)`. Here's a basic example

``` javascript
var nodeio = require('node.io')
   , options = {};

var job = new nodeio.Job(options, {
    input: false
  , run: function () { this.emit('foo'); }
});

nodeio.start(job, options, function (err, output) {
    console.log(output); // => [ foo ]
}, true);
```

You can then run this with `node test.js`.

Node used to have a hard 1GB limit but I believe this was lifted a few months ago. It sounds like your process might be running into some other issue

**Comment by ababushkin** [comment]
Thanks for the example Chris.

It turns out that jsdom has a memory issue, which is what was causing my application to die :)

**Comment by chriso** [comment]
No problems. I'd recommend using the default parser unless you need a full JS environment ;)
