### ISSUE TITLE
stuck after POST request

### ISSUE THREAD

**Issue by aldon-cmd** [node-js-libs/node.io#83]
after i submit the post form on www.aa.com I get stuck on the page saying "please wait"
shouldn't node.io's request stop on the last page that I am redirected to?

**Comment by aldon-cmd** [comment]
<meta http-equiv="refresh" content="5;URL=/blah/blah.com"  
when a page refreshes/redirects itself like this I have to manually follow the link. apparantly request.js has the same issue. https://github.com/mikeal/request/issues/92

var url = submitform.do?this=that;
var nextPage;
this.getHtml(url, function (err, $) {
            $('meta[http-equiv=refresh]').each(function (j, a) {
                nextPage = a.content.match(REgExp);//match a relative link in this attribute
            });
            url = "www.aa.com/" + nextPage;
            this.getHtml(url, parsePage);
        });

if there is a cleaner way to nest the requests please let me know

**Comment by chriso** [comment]
Unfortunately no, you'll need to parse the response to get the next url
