### ISSUE TITLE
builtin/pagerank: error thrown when the page does not have a pagerank

### ISSUE THREAD

**Issue by DavidBruant** [node-js-libs/node.io#86]
When a page doesn't have a pagerank, the following error is thrown:
TypeError: Cannot call method 'match' of undefined

Playing with the JS code, I discovered that for pages which do not have a pagerank, the data argument is set to undefined which obviously makes data.match(...) fail with the above error.

I'll let people who know coffeescript writing a fix because I'm fully incompetent in coffeescript, sorry :-s

**Comment by chriso** [comment]
Thanks for spotting this. Fixed in the latest release
