### ISSUE TITLE
Scraping local files

### ISSUE THREAD

**Issue by bebraw** [node-js-libs/node.io#87]
Hi,

I might be missing something obvious here but for some reason I couldn't figure out how to scrape local files using the API. I tried both getHTML and parseHTML (with this.read) without any success. As a result I ended up serving my files using a local server and using getHTML with that.

If it's not possible to scrape local files yet, could you please add some nice way to do that?

Thanks for node.io btw. It has helped a lot!

**Comment by chriso** [comment]
Hi Juho, `getHtml` is just a mashup of `get` and `parseHtml`. Try this

``` javascript
var self = this;
this.read(file, function (err, data) {
    self.parseHtml(data, function (err, $) {
       //... 
    });
});
```

**Comment by bebraw** [comment]
Awesome! Thanks. I think I know where I went wrong now. :)
