### ISSUE TITLE
Uniqueness of results before usage

### ISSUE THREAD

**Issue by samdelagarza** [node-js-libs/node.io#9]
This is fantastic! Currently I use a ruby script to scrape a web database, there's one thing that my script has that I'd love to see here. And that's the ability to validate the uniqueness of a record before writing to file or insertion in database. 
And with regards to the distribution across servers, I'm truly looking forward to this!

**Comment by chriso** [comment]
You could easily code this in yourself.. Something like this:

```
var seen_records = [];
exports.job = new nodeio.Job({}, {
    run: function () {
        var self = this;
        this.getHtml(url, function (err, $) {
            //Handle errors and scrape here..
            if (seen_records.indexOf(some_field) !== -1) {
                self.skip();
            } else {
                seen_records.push(some_field);
                self.emit(my_data); 
            }
        });
    }
});
```

Another option is to write to a file and then use the inbuilt [duplicates module](https://github.com/chriso/node.io/tree/master/builtin) to remove duplicates:

```
$ node.io -s duplicates < input.txt > duplicates_removed.txt
```

Happy scraping!
