### ISSUE TITLE
Default HTML parser and reddit example failing

### ISSUE THREAD

**Issue by crystalneth** [node-js-libs/node.io#93]
I tried the basic reddit example after my own code wasn't working. That also failed as it seemed to be parsing an empty string.

After digging into the node.io code, I found online 94 of dom.js, it calls htmlparser.done().  I don't understand the code well enough to know why this would be the case, but changing that line to this.htmlparser.parseComplete(data); allowed the example to work.

**Comment by jamesduncombe** [comment]
Got issues with that here too. You're right, changing that line fixes it! Nice one!

**Comment by chriso** [comment]
The request library kindly [changed](https://github.com/mikeal/request/commit/74ca9a4852b666d30dd71421e8cc8b8a83177148#README.md) its API without warning which broke the streaming parser.

Fixed in fd07c193919cd6939d38f457342b5aeaeb4cf9fe / `v0.4.9`
